### ISSUE TITLE
Add a 'lost connection to Kodi' message/indicator

### ISSUE THREAD

**Issue by deepdish1** [xbmc/chorus2#10]
just a suggestion : As you know, I use a kodi test on a VM.
It is quite interesting that if there s a problem on the central Kodi (for instance, I did not set the password properly to access to the music db)
Therefore, I could try to click and access one of the track and nothing was coming up and nothing was reporting to the chorus interface.
Maybe a warning could be welcome
food for thoughts

**Comment by jez500** [comment]
Not sure I understand, the UI loaded but it wasn't actually connected to kodi? or disconnected during use?

I plan on adding a "can't connect to kodi" message for the latter.

**Comment by jez500** [comment]
Added a 'disconnected' message when kodi quits and the option to attempt a reconnect afterwards
