### ISSUE TITLE
feature request: automatic/manual update of chorus2

### ISSUE THREAD

**Issue by Lemming0815** [xbmc/chorus2#101]
having to install the zip manually and checking for updates on the github is quite uncomfortable when wanting to stay up-to-date.
Can you include an update procedure? For a start, this may just be a button in the interface settings menu itself which will then pull the latest zip from the repo and install it.
In the future this could be automated, maybe integrated in the regular kodi update cycle as a standard plugin?

**Comment by dernalis** [comment]
I think Chorus2 is in some kind of beta version. 

I'm sure @jez500 will add to the kodi repositories in the future, just like Chorus(1).

**Comment by jez500** [comment]
Yep this will eventually make its way into the Kodi repo and replace Chorus 1, once that happens Kodi will update it automatically for you with each new release. 

This will happen when:
* Chorus 2 at a minimum matches functionality of Chorus 1
* As many bugs as possible have been ironed out

How you can help: 
* If you notice anything that Chorus 1 has but 2 is missing, post an issue
* If you notice any bugs post an issue

If you are an amazing person you can also submit a PR to fix those issues :)

**Comment by Lemming0815** [comment]
I will sure create issues for things I notice.
Thanks for the hard work. This is a really cool looking and much faster interface than chorus 1.
Is the plan to replace chorus 1 repo then or will it be an addition? In the latter case, you could ignore the 'matching
functionality' issue.##SELECTION_END##

**Comment by jez500** [comment]
Chorus 2 is now the default web interface that comes shipped with Kodi (v17 beta 6 onwards) and will get updates automatically just like other core addons.
