### ISSUE TITLE
feature request: Show Filepath in movie details

### ISSUE THREAD

**Issue by muhahacz** [xbmc/chorus2#102]
Would be great if you could display filepath to your movie (including movie name) for example in movie details.

Because for now there is NO web based library manager for KODI (Jarvis, for local db).

Its very unconfortable to check, if your movies were scrapped right. 
It could be easy in web interface to look, if movie was scrapped right or bad. Then you could rename it and scrapp it again. Or is there a better solution?

**Comment by PeterCodar** [comment]
Good idea. Please add such a path information also for music.
This would help to manually open songs in tagging programs.

**Comment by jez500** [comment]
As of 2.3.8 you can see file path info AND edit your media via `edit` in the contextual menu on songs, episodes, movies.

Should do the trick! ;)
