### ISSUE TITLE
List all song titles on one page

### ISSUE THREAD

**Issue by MrJoki007** [xbmc/chorus2#103]
It would be cool if you would implement a tab in the music section that lists all the titles because if i listen to music i want to see all the titles and add them to a playlist

**Comment by jez500** [comment]
This can put a huge load on your browser, my library for example has +50K songs which would immediately crash the browser. Lots of extra code and effort is required for this to work so unless there is great demand for this or someone else would like to implement, I recommend using the search or creating custom playlists.
