### ISSUE TITLE
[Feature] Music Library: add Genre (top level) browsing support (match Kodi GUI behavior)

### ISSUE THREAD

**Issue by arigit** [xbmc/chorus2#108]
Currently, Chorus2 offers 3 top-level options to browse the Music Library:
- Recent
- Artists
- Albums

This is Request to add one more option:
- Genres

and to match Kodi's GUI behavior/user experience:
- In Kodi, selecting Genres offers a list of the available Genres, e.g. Blues, Classical, Rock; upon selection of a Genre, Kodi GUI lists all artists that have an album categorized under that Genre; upon selecting an Artist from that list, Kodi lists all albums of the selected artist that belong to the Genre
  (currently, Chorus2 supports other use cases, as discussed [here](https://github.com/jez500/chorus2/issues/90))

Reason I submit is that the discussion in Bug 90 and the currently supported Chorus2 Filter, while super flexible does not cover the use case that Kodi offers by default and fits Audiophile use cases. Example: collection with 4000 albums, approximately 2000 of which are of Genre Classical: In Chorus2, selecting Music > Albums > Filter:Genre:Classical gives a huge list of 2000 albums, which is  of little use - the normal use case would be to then narrow down per Artist (typically encoding Composer info). This is exactly what the Kodi GUI does.

An alternative (and cool) way to add equivalent functionality to Chorus2 could be to add one more Filter option to allow filtering Albums by "Artist" as in:

Music > Albums > Filter:Genre:Classical + Filter:Artist:Beethoven

**Comment by jez500** [comment]
Added in 2.4.0
