### ISSUE TITLE
[Feature Request]Music: Add context menu points (like in General -> Main Nav settings)

### ISSUE THREAD

**Issue by PeterCodar** [xbmc/chorus2#116]
It would be great if we could add our own context menu entries, visible after pressing the 3 bullets (...) on a specific song.

I would like to add "Open in Mp3tag" and "Open song directory". 
Therefore, this setting should provide a solution to use commandline parameters for local installed 3rd-party apps.

**Comment by jez500** [comment]
As this is a web app, it can only create web urls, can you construct a web url that will open a local application?

**Comment by PeterCodar** [comment]
Maybe something like
<a href="file:///C:\Tools\Sound\mp3tag\mp3tag.exe">Link</a>
or one of this ideas:
http://stackoverflow.com/questions/22535148/how-to-open-local-file-in-browser
http://www.websina.com/bugzero/kb/browser-file-url.html
