### ISSUE TITLE
[Feature Request]Music: Hide "Thumbs Up" or setting to hide rating everywhere

### ISSUE THREAD

**Issue by PeterCodar** [xbmc/chorus2#117]
I don't like to see the rating function "Thumbs Up". 

I deleted the main menu entry in the settings. Works fine.
But the "Thumbs Up" icon is still visible on every single song.

Can you please hide this icon too?
Or make an additional setting to hide the "Thums Up" rating everywhere?

**Comment by jez500** [comment]
Added setting to toggle thumbs button visibility
