### ISSUE TITLE
missing stop button : due to browser :)

### ISSUE THREAD

**Issue by deepdish1** [xbmc/chorus2#12]

**Comment by jez500** [comment]
Any browser issues, please supply:
* Browser type and version showing the issue
* OS and version
* If visual, a screenshot

**Comment by uNiversaI** [comment]
I wonder if this is it... Did you press the remote button to access the stop control.

As a side topic thing.
I actually think the controls portion could be better organised and more functional/user friendly.

**Comment by jez500** [comment]
Closing due to not enough information
