### ISSUE TITLE
[Feature Request]Watched tick on 100% progress on TV shows

### ISSUE THREAD

**Issue by yoggi92** [xbmc/chorus2#121]
Hi!

Love the interface, the only thing I miss from original Chorus is the watched tick on 100% watched TV shows instead of the progress bar going all the way to 100%. 

One episode unwatched is really hard to see with a TV show that has a lot of seasons, where it can go up to 99.x% progress. I can see that the class is already there but it doesn't seem to generate a tick ones it reaches 100%.

Thanks!

**Comment by jez500** [comment]
Hey @yoggi92 have added episode count and much better 'watched' handling to tv shows in 2.3.6
