### ISSUE TITLE
Chorus playback problem

### ISSUE THREAD

**Issue by d3xt3r67** [xbmc/chorus2#122]
I'm having a lot of trouble with CHORUS2 ADDON for the video palyback.
I can stream my music without any trouble, but the video streaming (movies and TV shows) doesn't work at all. 
I log in the ADDON in CHROME (updated to the latest version) and I select a video to stream:

Problem #1: at the bottom of the windows I got the following error message: 
The media could not be loaded, either because the server or the network failed or because the format is not supported. 

Problem #2: After the error message , the Chorus logon windows pop several times even if I put my username password. 

About the error message, the video format is correct because I watched it before with the addon and the network is not the issue because I can stream my music with the addon.

I run GEEXBOX (geexbox-devel-20150819-r54bf816.cuboxi) on a CUBOX-I 4pro
KODI 16.1
CHORUS2 2.0.14

Am I the only one having this problem ???

**Comment by jez500** [comment]
Grab the latest version (2.0.16) it's not perfect but most mkv/mp4 now play correctly in Chrome (2ch audio only). not sure about problem number 2.

**Comment by d3xt3r67** [comment]
Thx I will try it today :)
