### ISSUE TITLE
use an opensource html5 media player that supports more A/V codec

### ISSUE THREAD

**Issue by marafa** [xbmc/chorus2#123]
i guess this is an **RFE**: use an opensource html5 media player that supports more A/V codec. 

**reason**: i have some mp4 that doesnt play.

**solution**: https://developer.jwplayer.com/ or if you need more choices http://upcomingweb.org/2012/07/html5-media-player.html

**Comment by jez500** [comment]
Chorus already uses one of those open source video players - http://videojs.com/

Codec support is determined by the browser. All those players will still require a codec used that the browser will support (and all browsers support different codecs). 

Kodi transcoding is the only solid solution for reliable playback in the browser http://forum.kodi.tv/showthread.php?tid=221503
