### ISSUE TITLE
Add possibility to add whole album to current playlist

### ISSUE THREAD

**Issue by janhicken** [xbmc/chorus2#124]
In Chorus 1, I could add a whole album to the list of currently playing songs by clicking the "+" icon while hovering over the album cover. We don't have that button any more, I'm only able to add single songs to the play list. 

Could we have this button back? I think it would also be a nice-to-have for adding the whole discography of a single artist / band.

**Comment by jez500** [comment]
Hi @janhicken 
You can do this via the context menu on a thumbnail now (clicking the 3 vertical dots) and then choose which playlist to add it to (local/kodi).

**Comment by janhicken** [comment]
Ah thanks, I missed that. 

Then I would say it's up to you to decide whether to save a click by adding an extra button is a meaningful enhancement.

**Comment by MartijnKaijser** [comment]
I think the context way is fine
