### ISSUE TITLE
A little bug with back button and breadcrumbs in Browse section.

### ISSUE THREAD

**Issue by pijo2004** [xbmc/chorus2#125]
I'm using twich and youtube plugin. When you open them true "Browse" section the back button does not work. I notice that in the json request is missing backslash (plugin://plugin.video.twitchcreateListOfGames/ it should be plugin://plugin.video.twitchcreate/ListOfGames/). After a few hours of reading I found out that this is not the only problem here. You create the breadcrumbs with url slit, but some of the plugins use url as parameters, so i have an idea and it's working but i don't know how to use github, how to show you my idea or even how to send you PM.
Best Regards

**Comment by jez500** [comment]
Hi @pijo2004 this should be fixed now 

https://github.com/xbmc/chorus2/commit/8ff801660b331164bcb749579b8f7f0fba510d13#diff-505998296e8c69c83ccbecafa33df918
