### ISSUE TITLE
Installation over addons/webinterface.kodi still shows old innterface

### ISSUE THREAD

**Issue by waitfor1t** [xbmc/chorus2#126]
Used install from zip method. Running osmc which uses kodi 16.1. Original files in webinterface.kodi got replaced but oddly enough the old interface still comes up. Do the files need to be copied to a document root?

**Comment by waitfor1t** [comment]
I think it might be better to use the webinterface.chorus2 identifier instead of overwriting.

**Comment by MartijnKaijser** [comment]
The ID has changed to webinterface.default and it will overwrite the default one

**Comment by waitfor1t** [comment]
OSMC (or maybe it's a Kodi thing?) seems to defer the web interface default in /usr/share/kodi/addons/webinterface.default, not in ~/.kodi/addons/webinterface.default. This means that when you overwrite webinterface.default in .kodi, you still see the old default. It's always risky to overwrite someone else's code, and here is a classic example of a bad practice. I will have to manually edit your files or manually put in /usr/share/kodi/addons. Since OSMC is widely used, I suggest you consider making an edit, at least in your installation instructions indicate an alternate install method for osmc.

**Comment by MartijnKaijser** [comment]
The current default web interface will die in a horrible fire and be replaced by this. If osmc us doing something special it's doing it all wrong.

**Comment by waitfor1t** [comment]
Agree on both counts. But it's a problem nevertheless, and if I had a penny for every workaround I did for other people's bugs, I'd be a billionaire. Maybe a note in your readme?

**Comment by MartijnKaijser** [comment]
There is no bug!

**Comment by waitfor1t** [comment]
I'm not implicating your work is a problem... I'm saying that you cannot install chorus2 on the current release of OSMC due to the above. OSMC protects the default web interface by caching it in /usr/share/kodi/addons.... So you need another install method if you want people to install on OSMC.

**Comment by MartijnKaijser** [comment]
Then go ask OSMC to stop doing such a stupid thing

**Comment by waitfor1t** [comment]
LOL - fair enough. However, hopefully this thread helps others. the workaround is to simply sudo cp -r ~.kodi/addons/webinterface.kodi /usr/share/kodi/addons and sudo rm -rf /usr/share/kodi/addons/webinterface.default

**Comment by hunagyp** [comment]
Just a side note, I experienced the very same "issue" on Ubuntu 16.0.4 LTS. This thread helped to sort out this issue for me, thanks a lot!
