### ISSUE TITLE
readd VLC Streaming

### ISSUE THREAD

**Issue by xinput** [xbmc/chorus2#127]
Hello There,

is there a way to re-add the Stream to VLC Option in the next version?
I'm having some trouble streaming my movies to my browser (caused by the HTML5 limitation only supporting movies with AAC Audio) So 90% of my movies have ac3 or DCA and it's not possible for me to stream them to my browser

Thanks in advance.

**Comment by jez500** [comment]
It should still be there, once you local play a video, you toggle it with the select box at the bottom of the player window. Although it doesn't work in chrome anymore because of this: https://support.google.com/chrome/answer/6213033

**Comment by xinput** [comment]
Thanks, i didn't noticed the little drop down.
too bad that it doesn't work anymore on chrome or firefox either
