### ISSUE TITLE
[Bug] playing all songs from an artist doesn't work

### ISSUE THREAD

**Issue by da-anda** [xbmc/chorus2#129]
Tested Chorus for the first time. Clicked on an artist and wanted to play all songs of this artist by pressing the "play" botton on the artist artwork. Nothing happened, also no error in the JS console etc. I suppose this button is dead atm?

**Comment by jez500** [comment]
Bug, it works clicking play on a thumbnail, will fix for the artist page too.

**Comment by jez500** [comment]
Hey @da-anda this one is fixed now in 2.3.4
