### ISSUE TITLE
Can not play music locally

### ISSUE THREAD

**Issue by bill-orange** [xbmc/chorus2#134]
I am running a Raspberry PI 3 using the nightly build of LibreElec. My music is stored on an external USB WD drive.  Choir2 works well and is reasonably fast except for one issue. 

I can not play music locally in the browser.  The progress counter does not advance and no sound is heard.  I have changed the port assignment from 8080 to 80 with no effect.  I have tried several browsers including Chrome and Edge.

Here is a log http://sprunge.us/eYTj 

Any troubleshooting suggestion?

**Comment by tommyknows** [comment]
I think I have the same issue. Is there any log for the webinterface itself?
I'm running Kodi 16.1 on a Debian (SteamOS) machine. My files are stored locally.

**Comment by bill-orange** [comment]
I started a thread on the KODI 17 forum here: http://forum.kodi.tv/showthread.php?tid=269814&pid=2456081#pid2456081

I think this has been a long standing issue that affects so few people that it has not been addressed.

**Comment by jez500** [comment]
@bill-orange does it work for music that is stored on the SD card? I know some people had issues in the past with Chorus1 the Pi and USB storage - https://github.com/jez500/chorus/issues/36

@tommyknows Any errors will display in the browser console

Unfortunately I don't have a Pi or SteamOS to test this, It  works fine for me using Chrome in OsX, Windows and Ubuntu

**Comment by bill-orange** [comment]
Yes! if the music is on the SD it streams fine.  I would appear that the virtual file system path passed to Corus2 is incorrect.  I will pass this on to the KODI forum.

**Comment by jez500** [comment]
closing as this is not a chorus issue
