### ISSUE TITLE
"Random" Section in Music

### ISSUE THREAD

**Issue by arigit** [xbmc/chorus2#135]
After selecting "Music" in the main panel, Chorus2 shows three sections: Recent / Artists / Albums

It would be great to have a 4th section: "Random Albums" that would show a list of 20 or 50 random albums from the library. For a large collection with thousands of albums, this is a great way to re-discover and explore - Yatse added this feature last year in the Music Overview and I find myself using it more often than not.

Another possibility could be a "Random" Section, with three subsections: Album (default) / Artist / Song
And then pehaps allow filtering the resulting list by Genre

**Comment by jez500** [comment]
A few new additions to 2.3.8 should get you pretty close, random albums on the music landing page and you could also add a random menu item with this path `music/albums?sort=random`. Let me know if this suits your needs

**Comment by arigit** [comment]
That's one huge step forward, thanks :)

Still thinking that  adding something like "Random Albums" (or "Discover your collection")  to the top level music menu would allow you to then Filter (by Genre would be the most useful).

Since this feature showed up in the Android remote I find myself using it all the time, I have a large collection of many thousands of albums and this is a nice way to rediscover it.

What about adding "Random" as one of the Sort options under Albums? that could be another way to achieve this. (offtopic but related: "Date Added" would also be useful as a Sort method - also supported by android remotes)

**Comment by jez500** [comment]
Hey @arigit 

Random and date added are both available filters for albums now

![random](https://cloud.githubusercontent.com/assets/782823/21577522/aaec991a-cfb1-11e6-97b7-3c41144b15c1.JPG)

**Comment by arigit** [comment]
Superb!! thanks! eagerly waiting for the next beta!
& hoping that Album Genre filters will make it to Kodi 17 as well :)

**Comment by arigit** [comment]
Tested 2.3.9 and it adds this functionality in the Music landing page. It's awesome, thanks for this great interface to Kodi.
