### ISSUE TITLE
v2.0.17 installation fails

### ISSUE THREAD

**Issue by Lemming0815** [xbmc/chorus2#138]
v2.0.16 worked but when I updated to .17, it just doesn't show as an option anymore. Its placed correctly under userdata and I can browse to ../addons/webinterface.kodi but nothing shows up there. The fallback automatically routes me to chorus1. Did I miss anything?
How can I "clean-install" via ssh only and not going through the kodi interface? I would like to have full control over the files placed into the filesystem.

The kodi.log registers an http error:
"ERROR: CWebServer: failed to handle HTTP request for /addons/webinterface.kodi"

**Comment by jez500** [comment]
The addon id has changed since that version. remove addons/webinterface.kodi folder and extract the zip to addons where it should replace addons/webinterface.default folder, then restart kodi.

See #126

**Comment by jez500** [comment]
Closing as Kodi v17-beta6 now ships with Chorus2 as webinterface.default 

https://github.com/xbmc/xbmc/pull/10989
