### ISSUE TITLE
Unauthorized to play music locally

### ISSUE THREAD

**Issue by tommyknows** [xbmc/chorus2#147]
Having an error that leaves me unable to play music locally.
The console error:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
However, all my music files on the system have rwx for everyone.
Also, the status report says that I need to allow remote control for kodi. 
I have enabled the control over UPnP and HTTP. My kodi remote app (iOS) works just fine. Also, "Allow remote control by programs on this system"  and "Allow remote control by programs on other systems" are both enabled. 
With what user does chorus try to read the files?

My status report:
```
Chorus version: 2.0.17
Kodi version: 16.1
Remote control: You need to 'Allow remote control' for Kodi. You can do that here
Local audio: HTML 5
```

**Comment by jez500** [comment]
I can't reproduce this. Chorus streams files via requesting a download from Kodi http://kodi.wiki/view/JSON-RPC_API/v6#Files.PrepareDownload
I suspect it is either a problem with your Kodi config or your file system
You are also using an older version of Chorus, perhaps update to the latest version?

**Comment by jez500** [comment]
Closing this as no response and most likely an old cache issue
