### ISSUE TITLE
Texts not currently translated

### ISSUE THREAD

**Issue by jairbubbles** [xbmc/chorus2#155]
*I'll update this as soon as I find new ones*

General:
- Just a sec... (supposed to be already translated)
- No results found
- Have you done a library scan?
- OK
- CLOSE

Music tab:
- Add filter

Filter:
- Title
- Year
- Date added
- Rating

Movie contextual menu:
- Add to Kodi playlist
- Edit
- Download
- Play in browser

Movie tooltip:
- Thumbs up
- Watched

Playlist tab:
- New playlist

Playlist contextual menu:
- Play in Kodi
- Play in browser
- Export in list
- Clear playlist
- Delete playlist

Options tab:
- General options
- SAVE

**All Kodi settings are not translated.**

**Comment by jez500** [comment]
I think all of the above should be translated in 2.3.7 now, please point out any missed strings or others found

**Comment by jez500** [comment]
Closing this, open a new issue if any more a spotted
