### ISSUE TITLE
Add ability to perform actions on a media set (eg. albums) in search results. Eg Add all albums to playlist

### ISSUE THREAD

**Issue by mrsharkbait** [xbmc/chorus2#156]
Currently, after performing a search, one can only browse the results, but unable to take the result set and perform actions on it.  For example, as of 2.3.5 I can only see a genre by apply it as a search filter.  (BTW, request [#108](https://github.com/xbmc/chorus2/issues/108) would be a great addition) Let's say it returns 10 albums.  If I want to play all 10 albums, I would have to navigate to each album and add it to a playlist.  This tedious task can be simplified if there were a context menu at a higher level that would allow me to add all to a playlist.  Unless, of course, there is such a feature which eluded me.

**Comment by jez500** [comment]
You can add each album to the playlist via the context menu in the album/artist/song teaser (3 dots) but not deal with a full set.

Interesting idea though, I am going to update the title of this one to be a bit less specific but still cover this requirement.

**Comment by mrsharkbait** [comment]
Agreed.

**Comment by jez500** [comment]
Context menu added to sets (in search/landing pages/genres) which allows you to 'select all' from there you can perform actions on selected items eg play, queue, add to playlist
