### ISSUE TITLE
Addons activation won't save

### ISSUE THREAD

**Issue by curunoir** [xbmc/chorus2#162]
Installed Kodi 17 beta 6 on Windows 10. 

Whenever I try to enable/disable any addon on the "Add-ons" Chorus2 tab, I scroll down to the Save button, a message "Toggled xxx addons" appear but when I came back to the tab nothing changed.
![chorus2ug](https://cloud.githubusercontent.com/assets/4137951/20970064/1789bcf8-bc8c-11e6-9636-af81af9699ac.PNG)

**Comment by jez500** [comment]
Thanks, is a bug, will be fixed with next release

**Comment by jez500** [comment]
This is fixed in 2.3.6

**Comment by curunoir** [comment]
Thanks.
