### ISSUE TITLE
Smart Playlists

### ISSUE THREAD

**Issue by jslinnhawkins** [xbmc/chorus2#167]
I cannot find, access any of my smart playlists.

**Comment by jez500** [comment]
Not currently available but I will add it. 

I don't think there is a way of creating them via the API atm but so I don't forget, this is to retrieve them:
`Files.GetDirectory ["special://profile/playlists/music"] `

**Comment by jez500** [comment]
As of 2.3.7 you should be able to find saved and smart playlists via the browser under sources & addoons

**Comment by jslinnhawkins** [comment]
Thanks - any chance the smart playlists can be added to the Movies and TV Series pages.  i use the Smart Playlist functionality to separate kids content from the main corpus. 

Great interface!
