### ISSUE TITLE
No audio when streaming video files

### ISSUE THREAD

**Issue by GhyslainBruno** [xbmc/chorus2#168]
Hi guys ! 

I'm just discovering the amazing job you've done with this new web interface. 

So here is the thing, when you start streaming any video file, the video flux is nicely streamed, but the audio isn't (even if it's AC3, not only if it's DTS, which I can understand shouldn't work).

Would be amazing if you knew how to solve this :-).

Thanks again for your job !

**Comment by jez500** [comment]
Glad you like it!

Unfortunately this is out of my control, for this to work we either need:
* Chrome (or other browsers) to support 5.1 sound codec via the html5 video tag
* Kodi to support transcoding, which is probably still a while away - http://forum.kodi.tv/showthread.php?tid=221503
