### ISSUE TITLE
PVR missing on recent direct route

### ISSUE THREAD

**Issue by mizaki** [xbmc/chorus2#17]
If you go directly to recent of tv shows or music the PVR is missing in "Sections". I guess it only works on the others as their calls take longer. Just need a change listener trigger when the addon call has completed?

**Comment by jez500** [comment]
Yeah, was a bit of a hackish way I did that - was hoping no one would notice ;)
I didn't want to delay the app init loading by waiting to get the addons first, I guess a listener could refresh that menu once addons are loaded, fairly edge case though and felt like it would require some messy code to rectify. That said in the future, there might be other menu items that are addon dependent so might be worth looking at a nice generic way of solving this.

**Comment by da-anda** [comment]
it appears PVR has been removed entirely? Are there any plans to add it back? I at least didn't get any PVR menu item in Chorus, nor is one available to activate in settings.

**Comment by da-anda** [comment]
just found it in "tv shows -> TV" node. Mind moving it up to the main menu and then also integrate PVR radio and recordings?

**Comment by jez500** [comment]
Hi @da-anda
You can customise the side menu, adding the functions you use the most via 'settings > main Nav'. As PVR requires addon installs I didn't list it as a default side menu item but very easy for a to add it themselves.

**Comment by jez500** [comment]
Lots of PVR improvements in 2.4.1
@mizaki direct route should be good now (menu refreshes after addons loaded)
@da-anda just for you - PVR added to side menu, recordings added too

**Comment by da-anda** [comment]
thanks @jez500

**Comment by Ralosso** [comment]
PVR doesnt work on OSMC with the IPTV simple Client Addon. 

also the "Favourites" are missing in Chorus. 

Maybe the links like "#pvr/tv" are not the same on OSMC?
Or how to get those?
