### ISSUE TITLE
download entire album

### ISSUE THREAD

**Issue by beankylla** [xbmc/chorus2#176]
Hello!

It would be very convenient to have the option to download an entire album and not just a song. 

In the end, it's rather practicall for people a bit on the go to be able to download a cd to listen to / change music a bit!

It's not really the point of the interface but if it were possible it would be awesone! :)

Thanks and have a nice day!

**Comment by jez500** [comment]
Kodi only supplies single files but this might be possible with https://stuk.github.io/jszip/ and some extra work in Chorus

**Comment by malard** [comment]
if the main app supports this, we can re-open this
