### ISSUE TITLE
Version still showing 2.0.16

### ISSUE THREAD

**Issue by microcreators** [xbmc/chorus2#178]
Not sure if it's only me, but 2.3.6 is still showing me "Chorus version 2.0.16" in HELP section. Yes, I've refreshed the cache. Otherwise all good 👍 
![screen shot 2016-12-22 at 14 22 57](https://cloud.githubusercontent.com/assets/12513837/21426967/29f2ec94-c852-11e6-9ec8-bc2914bfca2f.png)

**Comment by jez500** [comment]
I think it is only you :( Try installing the latest version via zip then force refresh of your browser. That number is picked from the addon.xml file so 99.999999% sure it us your browser cache... Also try another browser?
