### ISSUE TITLE
Addon not displayed in Browser (works in Yatse)

### ISSUE THREAD

**Issue by arigit** [xbmc/chorus2#182]
I have a simple Kodi addon I wrote myself, installed on 16.1/Jarvis, that doesn't have any UI, it can only be lanched: when launched it just calls an external python script.

This runs on a head-less kodi install that I manage via Chorus2 and Yatse. Yatse's "browser" displays my addon and I can launch it from Yatse (Android remote) with no issues, the addon launches my python script in the server, same as when I launch the addon on the server's UI (e.g. via a remote display / VNC)

Chorus2 lists the addons installed in the headless server except for my simple addon.

However I can see my addon installed in Korus settings, here:
    
    http://192.168.x.y/#settings/addons

(Under: xbmc.python.script)
AR - Start Spotify Connect
Starts Spotify Connect in the background

But in Chorus2 Browser (http://192.168.x.y/#browser), it's not listed:

Video
    Playlists 
Music
    Music
    SoundCloud
    TuneIn Radio
    Playlists 

I tried to add a custom menu entry in Chorus2 (http://192.168.x.y/#settings/nav) to launch this custom addon but it doesn't seem possible (couldn't find detailed documentation on URL paths to addons either)

Can Chorus2 Browser list all installed addons so they can be launched from the webUI?

**Comment by jez500** [comment]
Hey @arigit 

If you can add a route to your addon, you should be able to use it with Chorus. The browser expects a directory listing when requesting `plugin://addon.name` so if you added just one path then you would be able to bookmark it and use it as a side menu shortcut.

**Comment by arigit** [comment]
Hi Jez, I've been investigating this. My addon is a Kodi "script", it's not a video or audio plugin. Addon XML included below for reference. It appears that scripts can't return virtual folders, since they don't get assigned addon_handles like audio/video plugins do.

In Yatse (the android remote client) my 'script' addon shows up in the list of addons together with all other video/audio addons like TuneIn and RADIO. When I click it, it gets executed; Yatse doesn't display anything and does not seem to expect that the script will return a virtual folder either, it just works. Other addons like RADIO return a virtual folder that then you can navigate, same as with Chorus

Any chance we could have a similar functionality in Chorus? such that scripts get listed, and when clicked, they get executed

Alternatively: would it be possible to add a call to the script by adding a menu element pointing to script://script.connect.stop or similar (I'm not finding what the actual virtual path for scripts is)

Sorry if my question is basic and I'm missing something evident :) - any pointer could help

Thanks! 


-------------------------

<addon id="script.connect.stop" name="Stop Spotify Connect" version="1.0.0" provider-name="ar">
	<requires>
		<import addon="xbmc.python" version="2.14.0"/>
	</requires>
	<extension point="xbmc.python.script" library="addon.py">
		<provides>executable</provides>
	</extension>
	<extension point="xbmc.addon.metadata">
		<platform>all</platform>
		<summary lang="en">stop spotify connect</summary>
		<description lang="en">Stops Spotify Connect in the background</description>
		<license>GNU General Public License, v2</license>
		<language></language>
		<source>https://github.com/zag2me/script.hello.world</source>
		<email>test@kodi.org</email>
	</extension>
</addon>

**Comment by jez500** [comment]
Have a play with the API Browser in Chorus (lab > Api browser) and see if you can find the command that executes it, once we know that, can think about a nice generic way of implementing it. I'm guessing it will probably be `#lab/api-browser/Addons.ExecuteAddon`

**Comment by MartijnKaijser** [comment]
See if it's also available in our own android remote "Kore" which is actually opensource as well.
ping @SyncedSynapse or @poisdeux if they know

**Comment by arigit** [comment]
@jez500 - I did some tests with the Lab API browser and got the scripts to execute through the API, it was super easy.

I tested with two simple script addons, one launches a Spotify Connect client in the server, and the other one kills it. Their Addon IDs are "script.spotify.connect.start" and "script.spotify.connect.stop"

I captured the firefox console output:

```
Array [ "script.spotify.connect.start" ]  kodi-webinterface.js:488:14
 Response for: Addons.ExecuteAddon  kodi-webinterface.js:486:5
OK  kodi-webinterface.js:488:14
 Parameters for: Addons.ExecuteAddon  kodi-webinterface.js:486:5
Array [ "script.spotify.connect.stop" ]  kodi-webinterface.js:488:14
 Response for: Addons.ExecuteAddon  kodi-webinterface.js:486:5
OK
```

Now somehow the script addons would need to show up in the list given by:
 http://192.168.x.y/#browser

This is what yatse does, when navigating to Main menu > Addons, it lists all addons installed in Kodi (audio, video, and all scripts = xbmc.python.scripts , and you can execute them from there: audio and video addons return a virtual directory or start playing back some media, and scripts get executed)

**Comment by jez500** [comment]
@arigit - lucky I am holidays ;)

v2.3.9 - Add-on section added with the ability to browse and execute enabled addons
You can also execute an addon via a path too now Eg `#addon/execute/script.globalsearch` so with your example you could execute spotify with `#addon/execute/script.spotify.connect.start` 
This means you could add a custom menu item for your plugin now.

To see the new addons section `#addons/all` you might need to restore defaults in `#settings/nav`

**Comment by fatcatsanonymous** [comment]
Hi Jez500, I am triggering an addon which opens an overlay from the main menu. This is working in that it opens the overlay on the kodi interface when I execute the addon from the chorus2 menu, but not on the web interface. Rather than seeing the addon icon on the addons page when I activate the addon, I would like to see the overlay open over the "page" I'm on, i.e. music or video etc. Is this possible? Thanks for any hint as to how I might achieve this.
