### ISSUE TITLE
Help proposed

### ISSUE THREAD

**Issue by slash2009** [xbmc/chorus2#185]
Hi everyone,

Sorry to open an issue for this, but I would like to propose my help. I'm interested in two things:
- The new web interface is so neat that I would like to help in its evolution
- In the past I've created XWMM/WIMM in Javascript and I would like to re-write it with the same framework that Chorus 2 is using (also same look and feel if possible)
Any pointers to get me started would be appreciated.
Thanks

**Comment by jez500** [comment]
Hey @slash2009 

I would love it if you wanted to contribute to Chorus, especially with your experience in XWMM. Starting from scratch is a big task and also feels like it is re-inventing the wheel so would be much better to join forces. I already have in place the ability to do basic library edits with movies and have almost finished the functionality to do it with all media and a much more flexible edit experience.

You can see what is currently in place by clicking on the context menu on a movie teaser then clicking edit. The form that opens comes from this code: https://github.com/xbmc/chorus2/blob/master/src/js/apps/movie/edit/edit_controller.js.coffee

The new edit box is looking like this
![edit-movie](https://cloud.githubusercontent.com/assets/782823/21561058/8a32de92-cebb-11e6-8e64-6e3dd0abd918.JPG)

To get started, the first port of call is getting a build environment setup as all code is written in coffeescript/sass and then compiled to JS/CSS, checkout the readme for setup steps.

The project is well structured so once you start digging through [/src/apps](https://github.com/xbmc/chorus2/tree/master/src/js/apps) you should get a good idea where to find things

**Comment by slash2009** [comment]
Hi jez500,
I didn't notice the context menu but it is exactly what I would like to work on. This is great work.
I will start on build env. on my side and familiarize myself with coffeescript/sass (never used it before).
I will let you know how it goes.
Many thanks.
PS: Is there a way to contact you directly (irc, e-mail) if I have questions (not too many I hope)?

**Comment by jez500** [comment]
Hey @slash2009 

Grab v2.3.8 to see all the good new editing stuff, this is the commit that did it all https://github.com/xbmc/chorus2/commit/3bf4bf622c8a30b505365de902b29601cab74df7 

Once you get the hang of coffeescript and sass you'll never go back! it makes things so much easier

You can hit me up on email if you like, do a `git log` to see my email a million times ;)

**Comment by jez500** [comment]
Fanart and thumbnails editing added in 2.3.9 and live reloading of updated models + a pile of other improvements and fixes.

Unfortunately the api only allows updating images for tvshows and movies, I would love to add the same for artists and albums
