### ISSUE TITLE
Default Sort order for File Browser

### ISSUE THREAD

**Issue by robsee** [xbmc/chorus2#188]
Hi,

  When I use the file browser to look at my media store, there doesn't seem to be any sort of sort order applied. Is there an option I'm missing to alpha sort by name ?

Thanks

**Comment by jez500** [comment]
Yeah, I need to add the ability to change the sort order, you're correct, there is no order applied, which is correct for playlists (which orders by position) but annoying for everything else. It's on the list

**Comment by jez500** [comment]
Sort added to 2.4.0
