### ISSUE TITLE
Add the ability to "Play Using..." upnp registered devices

### ISSUE THREAD

**Issue by demonday** [xbmc/chorus2#191]
Just like the UI skin does it would be great if you could support the "Play Using..." upnp devices feature.

**Comment by jez500** [comment]
This is not supported by the API, there is some very experimental JS libs that might help but it looks doubtful. Have also played with chromecast streaming which wasn't very successful either

**Comment by linuxlurak** [comment]
this would be so great! in the meantime: do you know a upnp web ui (for linux systems)?
