### ISSUE TITLE
"Clear Playlist, Play" leads to unexpected behaviour

### ISSUE THREAD

**Issue by kopf** [xbmc/chorus2#195]
Steps required to produce:

* Play an album on Kodi via chorus2 until, say, track 6
* Clear the playlist
* Press "play" on another album
* Instead of beginning on track 1, as expected, it begins on track 7 (or so)

**Comment by jez500** [comment]
Fixed in 2.4.0

**Comment by kopf** [comment]
Great! Thanks!
