### ISSUE TITLE
Indicator on full season screen when episode is missing

### ISSUE THREAD

**Issue by Donald42** [xbmc/chorus2#199]
On the season overview screen, would it be possible to insert a "placeholder" entry when an episode is missing?  I know there are numbers at the bottom, but unless you are scanning them, it's pretty easy to overlook a gap. A toggle-able placeholder to show the gap would be a nice touch.

Thank you for all the hard work you have put into this new version.  It really looks terrific!

**Comment by jez500** [comment]
Kodi only provides what exists not what is missing so would need to hit some external api to get the missing items (slowing things down in the process). I also feel that this would be confusing as it is showing something that doesn't exist in your library. So very unlikely that I will add this, but if someone else would like to contribute a solution then I will consider it.

**Comment by Donald42** [comment]
I was just thinking along the lines of using the episode field in Video.Details.Episode (which I assumed was the episode number, but I don't know for sure!). If displaying the list in the season overview and there is an episode where the episode number isn't one greater than the previous, flag it in the display somehow to indicate a gap there, either by inserting a "dummy" item, or maybe just changing the background color of the episode where the gap occurs.

**Comment by jez500** [comment]
Yeah that could be done, but what if there are missing episodes after the last one you have in your collection? If it is going to have placeholders for the missing eps it should really show all missing eps not just the ones that fill gaps.

**Comment by Donald42** [comment]
I see what you mean... I really only noticed this in the first place because I watched an episode without realizing the one before it was missing. I wasn't worried about missing episodes at the end; only gaps between them.

**Comment by malard** [comment]
outside the scope of the web interface
