### ISSUE TITLE
Change background image(s)

### ISSUE THREAD

**Issue by Paul-Ver** [xbmc/chorus2#206]
With other webinterface addons, it's possible to navigate to the addons folder and change the images inside it (manually).

Is there a way without having to rebuild the source and/or keep the changed images after updating?
Or in what folder can I access the background files and replace them?

May also look at a way to make it configurable or dynamically linked (if it's not alread).

**Comment by jez500** [comment]
I was thinking about this recently, not sure the best way to attack it yet but on the todo list.

**Comment by Stooovie** [comment]
Any news on this? I'd be happy just to remove the images. I don't want to see the amplifiers all the time. Thanks!

**Comment by malard** [comment]
If you want this level of customisation, edit the package. Outside the scope of current development, however feel free to submit a PR
