### ISSUE TITLE
Movie info page not loading

### ISSUE THREAD

**Issue by sawoods** [xbmc/chorus2#207]
Clicking on a movie in the movie list just displays a spinning icon and 'just a sec' message.
Same issue if I install earlier versions 2.3.8, 2.3.9.
Working ok in 2.3.7.

Same/similar issue as mentioned in 2.3.9 release notes? :
"Bugfix - movie page not loading if no trailer (introduced in previous release)"

Status report -
Chorus version: 2.4.0
Kodi version: 16.1
Remote control: Remote control is set up correctly
Local audio: HTML 5
Browser: Chrome Version 55.0.2883.95 (64-bit) MacOS 10.11.6

**Comment by jez500** [comment]
Hi @sawoods 

Can you please open it inspector (CMD + SHIFT + I) and see if there are any errors that appear when you click on a movie page. It will likely explain what broke it.

If it is anything like that bugfix, the movie page might be expecting something that isn't there (in that case it was the trailer).

**Comment by sawoods** [comment]
Hi

From inspector in Safari I get this error when clicking on a movie:

[Error] Error code: -32602 - message: Invalid params.
	defaultExceptionHandler (kodi-webinterface.js:9:4281)
	c (kodi-webinterface.js:5:12234)
	handleExceptions (kodi-webinterface.js:9:4434)
	c (kodi-webinterface.js:5:12234)
	onError (kodi-webinterface.js:9:1917)
	c (kodi-webinterface.js:5:12234)
	(anonymous function) (kodi-webinterface.js:9:2542)
	c (kodi-webinterface.js:5:12234)
	k (kodi-webinterface.js:3:5897)
	fireWith (kodi-webinterface.js:3:6710)
	c (kodi-webinterface.js:4:20652)
	b (kodi-webinterface.js:4:26980)

With debug log turned on in Kodi there is this entry at the same time:

08:57:09 55743.265625 T:1738535920   DEBUG: webserver: request received for /jsonrpc?Movie
08:57:09 55743.269531 T:1738535920   DEBUG: JSONRPC: Value does not match any of the enum values in type
08:57:09 55743.269531 T:1738535920   DEBUG: JSONRPC: Array element at index 23 does not match in type properties

Hope that helps

Steve

**Comment by jez500** [comment]
Thanks Steve,

I think it must be this https://github.com/xbmc/chorus2/commit/3bf4bf622c8a30b505365de902b29601cab74df7#diff-c518f9ec54bb1dab1143064f61a13f20

Some new fields were added `'premiered', 'sorttitle', 'originaltitle', 'country', 'tag'` I suspect one of them is only available in v17. I'll have to build in version checking to fix, will look into it soon.

**Comment by jez500** [comment]
Should be fixed in 2.4.1 - the culprit was `premiered`
