### ISSUE TITLE
Please attach built files to releases instead of adding them to the source

### ISSUE THREAD

**Issue by rbalint** [xbmc/chorus2#209]
GitHub allows attaching prebuilt binaries, minified scripts to releases:
https://github.com/blog/1547-release-your-software

Distributing those there instead of in the source would help others in separating what is editable source thus would allow easier contributions.
I could also verify the copyrights of the files easier automatically. :-)

**Comment by jez500** [comment]
They are attached to releases https://github.com/xbmc/chorus2/releases

All source files are in the `/src` folder and at build, compiled into the `/dist` folder. `webinterface.default.2.X.X.zip` is just the `/dist` folder zipped up

**Comment by rbalint** [comment]
> They are attached to releases https://github.com/xbmc/chorus2/releases

@jez500 Ah, indeed.

> All source files are in the /src folder and at build, compiled into the /dist folder. webinterface.default.2.X.X.zip is just the /dist folder zipped up

Since they are already attached to the release they are really redundant in the git repo.

**Comment by jez500** [comment]
There is reasons for it being in the repo, amongst other things, it is a way for people to test before a release is created. It's only a few mb so it doesn't really hurt living in the repo too.
