### ISSUE TITLE
Sort albums by date added

### ISSUE THREAD

**Issue by kopf** [xbmc/chorus2#21]
(I'm not sure if you're accepting feature requests yet - if that's not the case, please close this issue, and accept my apologies for the annoyance!)

It'd be very useful to be able to sort albums (e.g. `/#music/albums`) by date added. The "Recently Added" view only shows the ~20 most recently added albums, which isn't very helpful in a lot of cases, especially when you add a lot of new music in a short space of time.

**Comment by jez500** [comment]
Hey @kopf 
Yeah I wanted that too however all the sorting is done on a fully loaded data set (the only way multiple filters can be applied) and unfortunately the [data set for albums](http://kodi.wiki/view/JSON-RPC_API/v6#Audio.Details.Album) doesn't include the date added (like it does for movies).  

I'll leave this open as might eventually find a way around this, but for now, building around the api limitation is a bit tricky.

**Comment by jez500** [comment]
Done! :)

**Comment by kopf** [comment]
Fantastic stuff! Thank you! :)
