### ISSUE TITLE
Add "album" column in search results

### ISSUE THREAD

**Issue by drt1** [xbmc/chorus2#212]
Heya,

it would be really great if you could add a album title column to the search results,
I guess between title and artist would be the best place.

Imagine you search for a title and find more than one,
because the library holds the studio-version and three live-versions,
you cannot identifiy the correct one you are searching for.

thank you for your great work!

best regards

**Comment by jez500** [comment]
done ;)

**Comment by drt1** [comment]
great, thanks man!
