### ISSUE TITLE
Ability to edit tags for TV Shows and Movies

### ISSUE THREAD

**Issue by GTunney** [xbmc/chorus2#215]
I use tags to tag all movies I want my son to watch on his Kodi upstairs into a "kids" category. Using XWMM there was an option to amend or add tags. Would it be possible to add this feature onto Chorus 2 when you get to edit a film or TV Show?

**Comment by jez500** [comment]
You can edit Movie tags in Chorus

![image](https://cloud.githubusercontent.com/assets/782823/21965873/b1b8afe2-dbbc-11e6-8ae7-ffecfc8c2dc8.png)

**Comment by GTunney** [comment]
I don't seem to get the same as above. I just get the below when I clock edit.

![ndg73xq](https://cloud.githubusercontent.com/assets/4008830/21965955/c23ac98c-db61-11e6-8696-365861ba24af.png)

**Comment by GTunney** [comment]
Please ignore me. Updated to latest commit and not have this feature.

Thanks.

**Comment by jez500** [comment]
Yep, That was added fairly recently 2.3.8 I think
