### ISSUE TITLE
Support for Music Videos

### ISSUE THREAD

**Issue by afoster** [xbmc/chorus2#217]
Hi

First up please excuse my lack of knowledge about Kodi and Chorus in general, I haven't been using either for long.

I've noticed Kodi (I'm using 17 rc2) has awareness of music videos, as distinct from movies, TV shows and audio-only songs. This [appears to extend to the API](http://kodi.wiki/view/JSON-RPC_API/v6#VideoLibrary.GetMusicVideos).

In my use case I have about 6,000 music videos which I'm hoping to remotely control using Chorus2 but its current functionality seems to be limited to the "Browser" nav item. 

1. Search doesn't return any results, probably because the several XHR calls to the JSON RPC API look specific to movies, TV shows and audio artists, albums and songs.

1. If I build a playlist of music videos via the Browser (playlist dots > add to playlist), I can save the playlist, but its contents can't be subsequently retrieved via `/#playlists`, probably because the call to `/jsonrpc?PlaylistCollection` returns each result item as a type `musicvideo`.

Is support for music videos on the roadmap, or is there a configuration option I'm missing?

Thanks!

**Comment by jez500** [comment]
Hey @afoster 

I haven't really thought about music videos much, mainly because they are so easy to stream these days but Kodi does have good support for them as does the [API](http://kodi.wiki/view/JSON-RPC_API/v6#VideoLibrary.GetMusicVideos) so is probably a worthy addition.

So it is on the roadmap now, stay tuned ;)

**Comment by afoster** [comment]
Thanks for the feedback! Given your architectural input, I am happy to contribute development muscle where helpful.

**Comment by jez500** [comment]
Music vids are now a first class citizen in Chorus! although with 6000 of them you may run into performance issues viewing them all, you can look them up with search too.

Thanks for your offer to help, I always welcome contributions, this is what went into adding music videos: https://github.com/xbmc/chorus2/commit/66d75cceb272ec71935d76d9d8405b0f97f911db

**Comment by afoster** [comment]
Amazing news @jez500 , thank you very much. I'll do some testing. 

I had noticed the performance issues and was going to suggest some form of pagination in some views, but that's a matter for another ticket.

Thanks again.

**Comment by karsta62** [comment]
I've looked everywhere, but can't find anything about musicvideos to put in the menu. Where / how?
Chorus version2.4.4
Kodi version17.6 on Libreelec / Raspberry Pi2

**Comment by Uatschitchun** [comment]
Hi, I'm running Kodi 18.4 with Chorus 2.4.6

I can't get musicvideos to be displayed?! Once I click on music->videos, I get nothing.

There are about 90 videos propperly added to kodi, but they do not show up in Chorus!? There's nothing in the logs either (debug log enabled).
