### ISSUE TITLE
Enable party mode functionality for local browser player

### ISSUE THREAD

**Issue by modulo-** [xbmc/chorus2#218]
Would it be possible to add the option of playing a Kodi playlist (or a snapshot of if) in the browser?

Personally I would like to use it for a Shuffle All feature via the browser while I am not at home.
Given that it is possible to view an instance of a Smart Playlist, it should also be possible to at least copy that instance to the browser storage (at it seems to me that this is how in-browser playlists work) similarly to playing an album in the browser. 
This would then potentially allow brute forcing a shuffle all by loading the whole library into the browser queue (and quite likely crashing the browser with larger libraries though...). A limited approach should be safe enough

Or perhaps a "Party Mode in Browser" option, that would reload a random selection once the Queue finishes, though this may be a bit more tricky to do.

Thanks,
Margus

**Comment by jez500** [comment]
interesting idea, party mode in the browser would probably be the best option - 10 random songs, then as a song finishes it gets removed and a new random song gets added to the end of the queue (pretty sure that's how the kodi party mode works). Would be even better to optionally specify the genre too, but I won't get ahead of myself :)

**Comment by modulo-** [comment]
Another somewhat related suggestion: adding "queue in browser" option, the old version had. 
Use case could be adding several albums or search results to the now playing.
A hacky workaround could be just to make the "Now playing in browser" playlist visible under "add to playlist"

**Comment by jez500** [comment]
Party mode is good to go for local in 2.4.3 it is not 100% robust but (if you try to do things like re-order playlist) but in general it works really well :)

Feel free to add a new issue for "queue in browser"

**Comment by modulo-** [comment]
Thanks!
This really made my day :) 
I run Kodi at home and forwarding the web interface port out over ssh is a simple and reliable solution while keeping the machine rather inaccessible.

**Comment by jez500** [comment]
No worries :) I'm enjoying this feature too
