### ISSUE TITLE
Use local video.js instead of CDN version

### ISSUE THREAD

**Issue by jez500** [xbmc/chorus2#219]
CDN version contains GA and would not work without an internet connection

See https://github.com/jez500/chorus/issues/145

**Comment by founderio** [comment]
After installing the most recent chorus2 on my Kodi I did check this again.
It seems that the 5.* version of video.js used here at least does not load GoogleAnalytics, unlike the 4.* version used in the previous chorus.
The issue with loading the external dependencies is still the same, though, so thanks for cross-linking that!

**Comment by jez500** [comment]
All local now :)
