### ISSUE TITLE
Caching of media library

### ISSUE THREAD

**Issue by mizaki** [xbmc/chorus2#22]
I've been considering how to keep an offline cache of the library and keep it synced when connected. It used to be if a movie was "refreshed" it was removed and added again with the updated info (with a new ID). This is no longer the case. It may be that we have to except in those cases we can not know (from a general sense) that this has happened.

As far as knowing new media has been added I should think it's as simple as checking the limits and then checking the last ID against the cache.

One of my worries has been about cache size (indexDB etc.) have a limited size (or not, bit of a mess). jez500 have you had any dealings with large local storage?

**Comment by jez500** [comment]
Hey @mizaki 
I am using [Backbone Fetch Cache](https://github.com/madglory/backbone-fetch-cache) for all the large collections thoughout the app which actually supports localstorage. But if the browser isn't connected, it doesn't know if the data has changed and doesn't know it has to invalidate the cache.  So, I have not enabled it. Also when fetching an individual model (Movie/Album/Etc) it is such a small request, I thought it would be best to grab a fresh update each time. Possibly something we could add to the settings though? 

I had to do a couple of hacks here and there to get this working correctly but nothing major.  Have also added a helper function that updates a key in a cached collection if a single property has changed (eg. watched status) so a full collection doesn't have to be retrieved again.

There is definite limitations with the amount of space available in local storage (I think most modern browsers are around 10mb) which would get chewed up very quickly when storing full collections (my movies request is about 3mb) and am worried that it would push out more valuable data like settings.  Although Backbone fetch cache does say it deals with local storage size "[intelligently](https://github.com/madglory/backbone-fetch-cache#user-content-cache-priority-in-localstorage)" 

Hope that (sorta) answered the question ;)
