### ISSUE TITLE
Addon content to playlist

### ISSUE THREAD

**Issue by Tommie1234** [xbmc/chorus2#226]
Hello,

I have been trying to add content from an addon (Soundcloud) to the play queue, but whenever I click on the menu button (three dots) it only displays a black bar with no options. It is possible to add the whole list to the queue with the menu button in the header.

I've tested it with other addons like YouTube and a Spotify add on and the same problem occurred. When I tried it with content I have in my library the button also worked for individual files and I was able to add them to the queu.

I have enclosed screenshots of the problem. It would complete my Chorus experience if this could be solved.

Thanks in advance

![addonplaylist](https://cloud.githubusercontent.com/assets/25490947/22524918/75287060-e8c5-11e6-89a3-8f157d4b0b2f.png)
![addonplaylist1](https://cloud.githubusercontent.com/assets/25490947/22524917/75277ee4-e8c5-11e6-901b-dd1add0ce8f6.png)

**Comment by jez500** [comment]
damn, that is a regression bug, will be fixed in next release, thanks for reporting it

**Comment by jez500** [comment]
Fixed in 2.4.3
