### ISSUE TITLE
Add "delete" to library items.

### ISSUE THREAD

**Issue by dernalis** [xbmc/chorus2#229]
Just like refresh option, even the code should be pretty similar.
Delete also the files would be asesome, but AFAIK the API just delete from database.

As case of use, it's usefull when a movie or tv show matches with a wrong one with same name, but not year. An easy an clean way to solve is rename the folder or file by adding the right year, but the old show or movie remains in library as a "dead link".

**Comment by eexit** [comment]
+1

Thanks!

**Comment by TullyMore** [comment]
While I can comprehend the use of a delete button, I would rather like to see it as a configurable option in a possibly password protected section under Settings > Kodi Settings (See [https://github.com/xbmc/chorus2/issues/272](url)) or maybe with a password request on every delete action. I'd rather not like to see users deleting media at will. Thanks.

**Comment by eexit** [comment]
> a password request on every delete action

Please don't. Unless you provide a way to batch delete action and password is required once.
Thanks!

**Comment by dernalis** [comment]
@TullyMore @eexit 
AFAIK, API just allow remove from database. **Media cannot be deleted**.
But there is a switch to allow or deny media delete from Kodi(2.4):
https://kodi.wiki/view/Settings/Media/General#Allow_file_renaming_and_deletion
