### ISSUE TITLE
Volume resets when playing a song in Local mode.

### ISSUE THREAD

**Issue by Zelaf** [xbmc/chorus2#230]
Whenever I use local mode and I play my music, I usually like to have it a bit quiter, but whenever I turn it down the audio gets reset to full.

I hope it's not ment to be like this.

Thanks for any help! :)

**Comment by jez500** [comment]
Currently it just defaults to 50% volume on load, should be straight forward to make it 'remember' the last volume and set that on page load. I'll look into it

**Comment by Zelaf** [comment]
Thanks ^^

**Comment by jez500** [comment]
Volume issue fixed in 2.4.4 which will roll out with the next Kodi release
