### ISSUE TITLE
Regression: Editing movie release date

### ISSUE THREAD

**Issue by ghotifish** [xbmc/chorus2#231]
In the movie edit window, the field for setting the release date (\<premiered\> in nfo, I think) seems to have disappeared. It would be nice to have that back.
Ideally, there would also be a way for setting only the year, when an exact date is not available, to fill the \<year\> field in the nfo.

**Comment by jez500** [comment]
I removed it because it is only available in 17+ and crashed the movie page in v16. It was a lot less work than adding version detection, once I work out a nice way of handling that I will add it back

**Comment by ghotifish** [comment]
Understood. Maybe you could add a year field in the meantime? That should have been around for a long time now.

**Comment by jez500** [comment]
Will definitely add year back in

**Comment by jez500** [comment]
Year added back now :) Grab 2.4.4 or wait for next Kodi release

**Comment by ghotifish** [comment]
Great, thanks! :-)
