### ISSUE TITLE
Changing the "Poster" does only change the thumbnail in Kodi, not the poster itself.

### ISSUE THREAD

**Issue by lukasgierth** [xbmc/chorus2#236]
So, i changed a couple of posters in the web interface and noticed that it only changes the thumbnail in the kodi instance and not the "real" poster.

**Comment by lukasgierth** [comment]
Looked a little bit into it. I don't even know if it is possible.

thumbnail and fanart are the only two fields related to images in VideoLibrary.SetMovieDetails that i could find.

**Comment by jez500** [comment]
I haven't really had any luck with media.artwork.set perhaps you could have a play with the `#lab/api-browser` and see if you can get it to work ;)

**Comment by lukasgierth** [comment]
Played a little bit with the api, no solution yet. Will continue my search

**Comment by tof06** [comment]
Hello, 
I'm new to this stuff, but here's what I send to JSONRPC Api to change a poster for a movie:
```
{ "jsonrpc": "2.0", "method": "VideoLibrary.SetMovieDetails", 
	"params": { 
		"movieid": 12,
		"art": {
			"poster":"https://image.tmdb.org/t/p/w640/sGyVDq1mj8oIc9wRIOxcVHfAIdN.jpg"
		}
	}, 	
	"id": 1 }
```
After this request, I need to send a `VideoLibrary.Scan` to refresh the library:
```
{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", 
	"params": { 	
	}, 
	
	"id": 2 }
```

I think it would be sufficient to scan only current source (there's a `path` parameter in `VideoLibrary.Scan` method), but did not test it.
