### ISSUE TITLE
Remote button blank until mouse over

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#24]
The remote button is blank which is hard to identify if thers any button whatsover there
###### Kodi info

Kodi (15.0-BETA2 Git:2015-06-05-0cb3841-dirty). Platform: Linux x86 64-bit
Kodi compiled Jun  5 2015 by GCC 4.8.2 for Linux x86 64-bit version 3.13.11 (199947)
Running on Ubuntu 14.04.2 LTS, kernel: Linux x86 64-bit version 3.13.0-53-generic
###### Browser Firefox 38.0.5

**_No mouseover**_
![capture](https://cloud.githubusercontent.com/assets/3521959/8039902/a7c8c1e8-0e04-11e5-9eee-385ff9a93ccf.PNG)

**_On mouse over**_
![untitled](https://cloud.githubusercontent.com/assets/3521959/8039876/756aaac2-0e04-11e5-819a-338aca1b83f2.png)

**Comment by jez500** [comment]
That's where it was in Chorus 1, while playing that box is the now-playing thumbnail. 
Agree you do have to know it is there, will look at adding it in additional places (maybe next to the search box or in the menu in the bottom right)

**Comment by uNiversaI** [comment]
I always thought that was a bug in Chorus 1 as well.
The button placement is just fine but if you have a roll-over image in disabled state for remote that becomes brighter when you roll-over that would take the guesswork out of it.

**Comment by jez500** [comment]
I'm going to close this one for now, I don't really want to pollute the playing thunb with a semi-opaque icon. I think a users guide is preferable #143
