### ISSUE TITLE
Media teasers should use a percentage rather than fixed width so they fill the screen better

### ISSUE THREAD

**Issue by skyway22** [xbmc/chorus2#241]
Loving the Chorus 2 web interface, definately changing to this.. 
But as i played along i saw some things and i want to report..
[Here](http://ultraimg.com/images/2017/02/15/p0Rn.png) is movie list with on my phone held in landscape mode. Everything showing ok, but when i held it in Portrait mode, [things](http://ultraimg.com/images/2017/02/15/p0RY.png) got [different](http://ultraimg.com/images/2017/02/15/p0Rv.png).. 
Also when clicking [these three dots](http://ultraimg.com/images/2017/02/15/p0RM.png) it shows a black thing..

**Comment by jez500** [comment]
Not sure what the difference is between the screenshots is? but the "black thing" is fixed in 2.4.3 - See #226

**Comment by skyway22** [comment]
By "different" i meant the empty space left to the right. In landscape mod those icons fill the display properly. In portrait mode doesn't.

**Comment by jez500** [comment]
Oh I see, yes the icons/thumbs are a fixed size for *reasons so if it will fill your screen depends on your screen size and dpi. I'm going to update the title of this issue to reflect that.
