### ISSUE TITLE
Still no volume control on keys outside keypad

### ISSUE THREAD

**Issue by SzymonZy** [xbmc/chorus2#242]
Hello

I use Kodi headless and still volume control does not work if you decide not to use keypad (I don't have one really).  Volume bar works but it is not clear for new users.

**Comment by jez500** [comment]
Hi! 

The `-` and `+` (not in the keypad) should work, if not go here: http://keycode.info/ and tell me the numbers that need to be added for vol up/down 

https://github.com/xbmc/chorus2/blob/2.4.3/src/js/apps/input/input_app.js.coffee#L103

**Comment by pijo2004** [comment]
@jez500 can you please add 61 for volume up and 173 for volume down and since we are on the subject can you look here https://github.com/xbmc/chorus2/blob/2.4.3/src/js/apps/input/input_app.js.coffee#L72 .You can see that you whitelisted '9' which is the "tab" number.

**Comment by jez500** [comment]
Extra keys added and tab removed from whitelist in 2.4.4
