### ISSUE TITLE
[Feature request] Using keyboard to type

### ISSUE THREAD

**Issue by nenadalm** [xbmc/chorus2#247]
hi. When keyboard appears on Kodi, I'd like to enter letters by typing them directly on my pc (rather than using arrow keys and enter). Currently that doesn't seems to be possible.

**Comment by Zelaf** [comment]
There should already come up a popup window inside Chorus with a text box, you enter the text there and click enter.

http://i.imgur.com/tARuvFr.png

**Comment by nenadalm** [comment]
I've tried it on another pc and it works. Thanks. Probably some issue with LibreElec (https://libreelec.tv/about/).

**Comment by zacchiro** [comment]
> I've tried it on another pc and it works. Thanks. Probably some issue with LibreELEC(https://libreelec.tv/about/).

did you find out what the problem was?
keyboard input doesn't work for me either, i'm also on libreelec, but i haven't found any other relevant issue tracker entry
