### ISSUE TITLE
Progress bars appear over the top of active filter bar

### ISSUE THREAD

**Issue by Etheral** [xbmc/chorus2#253]
![progress-issue](https://cloud.githubusercontent.com/assets/11221285/23828026/cdddfc1e-0717-11e7-8fcf-1f3dd44b769d.jpg)
when scrolling through a list of tv shows I noticed the show progress bars appear above the active filter bar at the top of the pages, I woudl assume this woudl occur for partailly watch movies as well.

this was seen in firefox 51.0.1 (64-bit) on windows 10 machine.

the progress bar divs (class entity-progress) have a z-index of 20. removing this fixes the issue however I'm not sure if this will cause issues elsewhere.
another option is to give the active filters bar (class filters-active-bar) a z-index higher than 20.

**Comment by jez500** [comment]
Hi, thanks for finding that, fixed in 2.4.4
