### ISSUE TITLE
3 dots next to item: click reveals black box, nothing in it

### ISSUE THREAD

**Issue by TechAndNews** [xbmc/chorus2#258]
Firefox 52.0.1 (64-bit) 
LinuxMint 17.3 XFCE (64-bit)
Kodi 17.0 (stable) 
Wired Ethernet (all devices) 
![kodi-chorus2-bug](https://cloud.githubusercontent.com/assets/7966743/24303360/10a1e1aa-108c-11e7-89a2-aac0861e399c.png)

**Comment by jez500** [comment]
Update to either latest chorus or latest kodi to fix this

**Comment by TechAndNews** [comment]
Updating from 17.0 to 17.1 fixed the issue. 

Now, a left-click on the 3 dots next to an item says, "Queue in Kodi."

And it works for Files on my LAN File-Server.

But it does not work for URLs from Addons like YouTube.
