### ISSUE TITLE
not used libs in addon.zip

### ISSUE THREAD

**Issue by CvH** [xbmc/chorus2#262]
I found `dist/lib/video-js/video-js.css` and `dist/lib/video-js/video.js` included at addon.zip.
From my understanding and looking at the running web interface only the .min.js is used at all.

Also I found `base\fonts\icomoon\demo.html`, `base\fonts\icomoon\demo-files` and `base\fonts\icomoon\selection.json` as unused files.

Also I am pretty sure that the 8 different fonts + .eot, .svg, .ttf, .woff, .woff2 of each font are really used at all.

Is there any particular reason to include it ?

**Comment by jez500** [comment]
The demo files are useful for debugging but could probably go or at least be moved out of the dist folder and potentially added to the build.

The different fonts are for browser compatibility, unfortunately the is not a universal standard.

**Comment by CvH** [comment]
@jez500 as we (at LE) need to bake the addon into the image every MB counts. As >99,99% of the users are not debugging, it is from my pov a fair trade to save ~20% file size, if you can debug this you can also access gh ;)

About the fonts I can't really help, afaik there are oss fonts that support all browsers and have multible font faces included ?

**Comment by malard** [comment]
the content in question represents about 250kb of data and the request to improve this has not been followed up in 7 years, closing
