### ISSUE TITLE
Chorus - no sound playing locally in browser

### ISSUE THREAD

**Issue by duncspur** [xbmc/chorus2#264]
Hi All,

I'm having a problem playing files locally in my browser. I can see them playing but there is no sound in Chrome. Other sites work okay. At first I thought it was FLAC files but MP3s are also mute. I'm sure it's just a simple setting. What am I doing wrong?

Best, Duncan

**Comment by Zelaf** [comment]
Have you resolved the problem?

Are all your audio settings OK? Have you tried other devices? Do you see any error messages in the console of the browser (press f12 and then go to Console)?

**Comment by duncspur** [comment]
Hi, thanks for replying. No, I've not solved it. I've tried other devices and I'm getting the same problem on those too. I did get this on the Console though:

kodi-webinterface.js:538  Websockets Active
kodi-webinterface.js:15 soundManager: useFlashBlock is false, 100% HTML5 mode is possible. Rebooting with preferFlash: false...
U @ kodi-webinterface.js:15
/vfs/%2fvar%2fmedia%2fElements%2fMusic%2fPink%20Floyd%2fZabriskie%20Point%20Session%2f01%20Rain%20in%20the%20country.mp3 Failed to load resource: the server responded with a status of 401 (Unauthorized)
/#music:1 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by duncspur** [comment]
Sorry - didn't mean to close it!!

**Comment by Zelaf** [comment]
So you are unauthorized to load the actual media. Can you try to disable flash on the website/browser in addon settings of the browser? Probably won't work but worth a try.

**Comment by jez500** [comment]
Also see if you can just download the song directly using chorus (in the context menu for a song), sounds like a permissions error of some sort

**Comment by kikendo** [comment]
I think I am having the same issue, (https://github.com/xbmc/chorus2/issues/280) and I have HTML5 only (no flash) and trying to download just leads to a blank screen. It used to work, though, I had Chorus playing music in some browsers and download always worked. What setting pertains to this?

**Comment by mantebridts** [comment]
Same issue as @kikendo describes. Is there anything we can do to fix this? :)

**Comment by kikendo** [comment]
@mantebridts I found a workaround online that I posted here: https://github.com/xbmc/chorus2/issues/289
It works just great.

**Comment by mantebridts** [comment]
@kikendo Thx for the hint! I had to change the path to the media, but afterwards it works fine! 👍

**Comment by enrigo** [comment]
Hi All,
the workaround posted by kikendo doesn't work for me on kodi 18.x. Tried on 3 different PC with 3 different browser, audio files play but no sound at all.
Any other hint?

**Comment by malard** [comment]
closing as this isn't happening in 20.x and has not been commented on in nearly 4 years
