### ISSUE TITLE
[IDEA] Support for web-links and local videos

### ISSUE THREAD

**Issue by eidermar** [xbmc/chorus2#267]
Love Chorus 2!!!

I'd like to make a suggestion for an additional feature though. It would be very cool if it was possible to drag&drop local videos to the interface so they start playing in Kodi. Also if it was possible to copy&paste or drag&drop links to web-videos that would be even better. There are extensions for Firefox ([see here](https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc/)) and Chrome ([see here](https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden?hl=en)) that have this functionality. I have no idea if it's even possible, but that would make a great addition to chorus in my opinion.

Thanks for sharing this beautiful webinterface.

**Comment by jez500** [comment]
Glad you like it!

Dragging and dropping would only work if you are using chorus on the same pc that is running kodi, and even then there is issues if that video isn't in a kodi source. The reasons why those extensions work is you are using a public web url (which is available from anywhere) but a local file is not.  Neat idea, but will have to say no as it will not work more times than it would work.

What I wouldn't mind adding is a "Play remote file" popup where you could paste in a video url and that would play in kodi.

**Comment by eidermar** [comment]
Thanks for your reply!

I'd love to see the "Play remote file" via popup feature!!!
