### ISSUE TITLE
URL login

### ISSUE THREAD

**Issue by chrisc25** [xbmc/chorus2#269]
Hello I have a app I use for home automation, I have made an iframe redirecting to:

http://username:password@mykodiip:mykodiport

It does not work, I just get the loading application when I upload my files to android.

Please could you tell me how, i have a webserver, and very basic knowledge of code.

Any help would be appreciated (ps login box wont appear through the app, and i really like the idea of it automatically logging in).

**Comment by jez500** [comment]
Pretty sure that is a browser security issue (http basic auth in iframe). If you are going to expose the username and password, you might as well just not use it and ensure your kodi instance is only available on your local network.

**Comment by jez500** [comment]
Closing due to no response and issue is caused by browser security over app.
