### ISSUE TITLE
Power option in remote

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#28]
In Chorus 1 you press the power button in remote and you get a pop up with some options. You select the option you want and presto.

In Chorus 2 You press the power button and Kodi immediately exits a message (Kodi has quit) is displayed in Chorus 2.

I also have a suggestion regarding system messages. Atm they are displayed on the bottom right corner, if you blink you miss them. (I suppose this mimics some system notification in tray)

It would be better perhaps to use a position people expect messages to pop up like center of the window in some sort of box that indicates "Hello Im a system message"

Else make the message in a box pop up where it currently is just give it some more prominence within the window so its not easily missed.

**Comment by jez500** [comment]
Power option:
Yes this is incomplete, the plan is to add all power options like Chorus 1

Notifications:
Might play around with the styles, possibly add a setting to adjust the display time? But yes, it was intended to mimic system notifications, something subtle and doesn't get in the way but still obvious.

**Comment by uNiversaI** [comment]
I think half the problem is old age but since you cant fix that, I made this report instead :)

**Comment by schumi2004** [comment]
Will this be fixed anytime soon?

**Comment by jez500** [comment]
You now get a nice popup with quit/shutdown/reboot/suspend/hibernate - will also check if device allows all of these before showing the option
