### ISSUE TITLE
Local music playback almost never works.

### ISSUE THREAD

**Issue by kikendo** [xbmc/chorus2#280]
I have tried this many times on different machines and browsers with mixed results.
Windows 7 PC with Chrome: local media shows up on playlist, hit play, nothing happens, time counter stuck at zero.
Windows 7 PC with Vivaldi: local media shows up on playlist, hit play, nothing happens, time counter stuck at zero.
Powermac G5 with tenFourFox latest version : used to work fine (only computer I managed to get it running!) but as of recently it stopped working too. Same symptons as above.
Windows Phone running Edge: same issues as above.
iPad running Chrome: same issues as above, but I think it used to work.

Chorus version 2.4.4
Kodi version 17.1
Remote control Remote control is set up correctly
Local audio HTML 5

When it was working I had the previous Kodi version, latest 16.x. I had manually installed Chorus 2 on it.
This is running in OpenELEC on a rPi 3.

I notice that "downloading" the media also doens't work. Lands on an empty page. is this a settings problem?

I hope this can be fixed, it was awesome when I could play on my browser! Videos never play (always get "media not supported") but at least having music would be awesome.

**Comment by jez500** [comment]
If downloading doesn't work then this is the cause of the streaming not working, I think there might be an issue with openelec and usb storage, can you test with media on the sd card and see if it works?

**Comment by kikendo** [comment]
Jez500, media on the SD storage is downloadable. DOesn't seem to allow me to "play locally" as an option, but I managed to download a tune.

My main confusion is that this was working until I updated to 17.x , not on every machine, but at least my G5 with tenFourFox was running just fine.

Thanks for looking into this! I love Chorus!
Let me know how else I could help.
