### ISSUE TITLE
Allow username/password in URL to connect

### ISSUE THREAD

**Issue by nuentes** [xbmc/chorus2#283]
I was wondering if it's possible to create a URL that automatically logs me in. The first example I can think of is NZBGet, where I can enable password protection, and then set the URL to localhost:6789/nzbget:tegbzn6789/ (nzbget being the default username, and tegbzn6789 being the default password). Navigating to this will automatically log me in to the site, and keep me logged in. Is anything like this possible in chorus2?
Edit - just saw this is the same request as #269, but I'd like to keep this open as an enhancement request.

**Comment by jez500** [comment]
Would something like http://user:password@kodi-ip work?

**Comment by nuentes** [comment]
Oof. Sorry I never replied.

I was thinking about this today, and realized my issue with the way login occurs is through a prompt within the browser, rather than a splash webpage. If there were a splash webpage to login to, then I would be able to login with my password manager app. My password manager can't login via the browser prompt. Is something like that possible?

**Comment by malard** [comment]
closing, modern password managers are able to support the current login method far better than 7 years ago
