### ISSUE TITLE
Local play for files excluded from library

### ISSUE THREAD

**Issue by igitur** [xbmc/chorus2#285]
I have a bunch of files that are on my Kodi device, but are not scanned into the library. I use Chorus' Browser menu item to access them. I would like to play them inside the Chorus interface on my client machine (not on the Kodi machine). This doesn't seem to work. I can choose Download and luckily my client's Chrome browser would play it in a new tab, but I would prefer the files to play locally like any other video that is part of the library.

**Comment by malard** [comment]
chorus will only play content that is in the library
