### ISSUE TITLE
Kodi Reload after start a Video with the Netflix App

### ISSUE THREAD

**Issue by Jefferson-goxts** [xbmc/chorus2#286]
21:06:13.534 T:1706390432   DEBUG: -->Python Interpreter Initialized<--
21:06:13.534 T:1706390432   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.netflix/service.py): the source file to load is "/storage/.kodi/addons/plugin.video.netflix/service.py"
21:06:13.552 T:1698001824   DEBUG: CPythonInvoker(3, /storage/.kodi/addons/service.system.dispmanx_vnc/default.py): instantiating addon using automatically obtained id of "service.system.dispmanx_vnc" dependent on version 2.1.0 of the xbmc.python api
21:06:13.661 T:1706390432   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.netflix/service.py): setting the Python path to /storage/.kodi/addons/plugin.video.netflix:/storage/.kodi/addons/script.module.beautifulsoup4/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/share/kodi/addons/script.module.pycryptodome/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
21:06:13.661 T:1706390432   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.netflix/service.py): entering source directory /storage/.kodi/addons/plugin.video.netflix
21:06:13.664 T:1706390432   DEBUG: CPythonInvoker(2, /storage/.kodi/addons/plugin.video.netflix/service.py): instantiating addon using automatically obtained id of "plugin.video.netflix" dependent on version 2.24.0 of the xbmc.python api
21:06:16.248 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:16.249 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:16.250 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:16.251 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:16.251 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:16.251 T:1706390432   DEBUG: CSettingsManager: requested setting (logging) was not found.
21:06:16.256 T:1706390432   DEBUG: [Netflix] MSL Data exists. Use old Tokens.
21:06:16.359 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:16.359 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:16.361 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:16.361 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:16.361 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:16.361 T:1706390432   DEBUG: CSettingsManager: requested setting (logging) was not found.
21:06:16.363 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:16.363 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:16.364 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:16.364 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:16.364 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:16.405 T:1706390432   DEBUG: [Netflix] Building User Agent for platform: Linux - armv7l
21:06:16.408 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:16.408 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:16.410 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:16.411 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:16.411 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:16.414 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:16.414 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:16.416 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:16.417 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:16.417 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.516 T:1706390432   DEBUG: [Netflix] [GET] Request for "https://www.netflix.com/profiles/manage" took 1.0955350399 seconds
21:06:17.628 T:1706390432   DEBUG: [Netflix] Trying sloppy inline data parser
21:06:17.639 T:1706390432   DEBUG: [Netflix] Sloppy inline data parsing successfull
21:06:17.689 T:1706390432   DEBUG: [Netflix] Ignoring exception for non Android devices
21:06:17.691 T:1706390432   DEBUG: [Netflix] Found ESN "XXX"
21:06:17.693 T:1706390432   DEBUG: [Netflix] Is FILE: True
21:06:17.695 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.695 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.696 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.697 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.697 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.697 T:1706390432   DEBUG: [Netflix] XXX
21:06:17.698 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.698 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.700 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.700 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.700 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.702 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.702 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.704 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.704 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.704 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.704 T:1706390432   DEBUG: CSettingsManager: requested setting (logging) was not found.
21:06:17.709 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.709 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.710 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.711 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.711 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.714 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.714 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.716 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.716 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.716 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.716 T:1706390432   DEBUG: [Netflix] [MSL] Picked Port: 55077
21:06:17.718 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.718 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.720 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.721 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.721 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.727 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
21:06:17.727 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
21:06:17.730 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
21:06:17.730 T:1706390432   DEBUG: CSettingsManager: requested setting (setting) was not found.
21:06:17.730 T:1706390432   DEBUG: CAddonSettings[plugin.video.netflix]: failed to find definition for setting setting. Creating a setting on-the-fly...
21:06:17.736 T:1706390432   DEBUG: [Netflix] [NS] Picked Port: 49399

########################### AT THIS TIME KODI IS RELOAD... o.O ##################################

21:06:18.135 T:1754264480    INFO: ## LibreELEC Addon ## system::set_hostname ## JeffMediaCenter
21:06:18.137 T:1754264480    INFO: ## LibreELEC Addon ## system::set_keyboard_layout ## de
21:06:18.137 T:1754264480    INFO: ## LibreELEC Addon ## system::set_keyboard_layout ## loadkmap < `ls -1 /usr/lib/keymaps/*/de.bmap`
21:06:18.251 T:1754264480    INFO: ## LibreELEC Addon ## system::updateThread ## Started
21:06:18.251 T:1754264480    INFO: ## LibreELEC Addon ## system::set_auto_update ## auto
21:06:18.324 T:1569661856    INFO: ## LibreELEC Addon ## _service_::run ## WAITING:
21:06:18.342 T:1578050464    INFO: ## LibreELEC Addon ## xdbus Monitor started. ##
21:06:18.974 T:1942650896   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
21:06:22.428 T:1942650896   DEBUG: ------ Window Init (Pointer.xml) ------
21:06:25.276 T:1942650896   DEBUG: Keyboard: scancode: 0x64, sym: 0x0139, unicode: 0x0000, modifier: 0x0
21:06:25.276 T:1942650896   DEBUG: GetActionCode: Trying Hardy keycode for 0xf200
21:06:25.276 T:1942650896   DEBUG: Previous line repeats 3 times.
21:06:25.276 T:1942650896   DEBUG: OnKey: 0 (0xf200, obc-61697) pressed, action is
21:06:25.278 T:1942650896   DEBUG: ------ Window Deinit (Pointer.xml) ------
21:06:25.476 T:1942650896   DEBUG: Keyboard: scancode: 0x64, sym: 0x0139, unicode: 0x0000, modifier: 0x0
21:06:26.811 T:1561273248   DEBUG: CWebServer[8080]: request received for /jsonrpc?Application.GetProperties
21:06:26.815 T:1561273248   DEBUG: CWebServer[8080]: request received for /jsonrpc?Player.GetActivePlayers

KODI Crash Log:

21:31:17.907 T:1495524256   DEBUG: AddOnLog: InputStream Adaptive: Download https://ipv4_1-mce0-c002.1.fra001.dev.ix.nflxvideo.net/?o=XXX finished, average download speed: 634841.8696
21:31:17.907 T:1495524256   DEBUG: ProcessPacket - audio:32 video:33
21:31:17.908 T:1495524256   DEBUG: Previous line repeats 1 times.
21:31:17.908 T:1495524256   DEBUG: ProcessPacket - audio:32 video:34
21:31:17.908 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.908 T:1495524256   DEBUG: ProcessPacket - audio:32 video:35
21:31:17.908 T:1495524256   DEBUG: ProcessPacket - audio:33 video:35
21:31:17.909 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.909 T:1495524256   DEBUG: ProcessPacket - audio:34 video:35
21:31:17.909 T:1495524256   DEBUG: ProcessPacket - audio:34 video:36
21:31:17.909 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.909 T:1495524256   DEBUG: ProcessPacket - audio:34 video:37
21:31:17.909 T:1495524256   DEBUG: ProcessPacket - audio:35 video:37
21:31:17.909 T:1495524256   DEBUG: Previous line repeats 1 times.
21:31:17.909 T:1495524256   DEBUG: ProcessPacket - audio:35 video:38
21:31:17.910 T:1495524256   DEBUG: ProcessPacket - audio:36 video:38
21:31:17.910 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.910 T:1495524256   DEBUG: ProcessPacket - audio:36 video:39
21:31:17.910 T:1495524256   DEBUG: Previous line repeats 1 times.
21:31:17.910 T:1495524256   DEBUG: ProcessPacket - audio:37 video:39
21:31:17.910 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:37 video:40
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:38 video:40
21:31:17.911 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:38 video:41
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:39 video:41
21:31:17.911 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:39 video:42
21:31:17.911 T:1495524256   DEBUG: ProcessPacket - audio:40 video:42
21:31:17.912 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:40 video:43
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:41 video:43
21:31:17.912 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:41 video:44
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:42 video:44
21:31:17.912 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:42 video:45
21:31:17.912 T:1495524256   DEBUG: ProcessPacket - audio:43 video:45
21:31:17.913 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:44 video:45
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:44 video:46
21:31:17.913 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:44 video:47
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:45 video:47
21:31:17.913 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:46 video:47
21:31:17.913 T:1495524256   DEBUG: ProcessPacket - audio:46 video:48
21:31:17.914 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:46 video:49
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:47 video:49
21:31:17.914 T:1495524256   DEBUG: Previous line repeats 1 times.
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:47 video:50
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:48 video:50
21:31:17.914 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:48 video:51
21:31:17.914 T:1495524256   DEBUG: Previous line repeats 1 times.
21:31:17.914 T:1495524256   DEBUG: ProcessPacket - audio:49 video:51
21:31:17.915 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.915 T:1495524256   DEBUG: ProcessPacket - audio:49 video:52
21:31:17.915 T:1495524256   DEBUG: ProcessPacket - audio:50 video:52
21:31:17.915 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.915 T:1495524256   DEBUG: ProcessPacket - audio:50 video:53
21:31:17.915 T:1495524256   DEBUG: ProcessPacket - audio:51 video:53
21:31:17.916 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.916 T:1495524256   DEBUG: ProcessPacket - audio:51 video:54
21:31:17.916 T:1495524256   DEBUG: ProcessPacket - audio:52 video:54
21:31:17.916 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.916 T:1495524256   DEBUG: ProcessPacket - audio:52 video:55
21:31:17.916 T:1495524256   DEBUG: ProcessPacket - audio:53 video:55
21:31:17.917 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.917 T:1495524256   DEBUG: ProcessPacket - audio:53 video:56
21:31:17.917 T:1495524256   DEBUG: ProcessPacket - audio:54 video:56
21:31:17.917 T:1495524256   DEBUG: Previous line repeats 3 times.
21:31:17.917 T:1495524256   DEBUG: ProcessPacket - audio:54 video:57
21:31:17.918 T:1495524256   DEBUG: ProcessPacket - audio:55 video:57
21:31:17.918 T:1495524256   DEBUG: Previous line repeats 2 times.
21:31:17.918 T:1495524256   DEBUG: ProcessPacket - audio:56 video:57
21:31:17.918 T:1495524256   DEBUG: ProcessPacket - audio:56 video:58
21:31:17.919 T:1495524256   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Connection: keep-alive'
21:31:17.919 T:1495524256   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=1163769-1594176'
21:31:17.919 T:1495524256   DEBUG: CurlFile::Open(0x53165e28) https://ipv4_1-mce0-c002.1.fra001.dev.ix.nflxvideo.net/?o=XXX
21:31:17.925 T:1414525856   ERROR: CMMALRenderer::Process - Failed to send omvb:0x72a3c818 mmal:0x70dbee40 to vc.ril.video_render:in:0(I420) (status=03 EINVAL)
21:31:17.958 T:1414525856   ERROR: CMMALRenderer::Process - Failed to send omvb:0x72a0c840 mmal:0x70dbf018 to vc.ril.video_render:in:0(I420) (status=03 EINVAL)
21:31:18.009 T:1414525856   ERROR: CMMALRenderer::Process - Failed to send omvb:0x72a00b78 mmal:0x70dbf1f0 to vc.ril.video_render:in:0(I420) (status=03 EINVAL)
21:31:18.277 T:1511515040   ERROR: CMMALPool::GetBuffer - failed pool:0x5f198910 omvb:(nil) mmal:(nil) timeout:500
21:31:18.277 T:1511515040   ERROR: CAddonVideoCodec::GetFrameBuffer Failed to allocate buffer

**Comment by jez500** [comment]
Closing as this has nothing to do with Chorus. Advise you check with the addon devs
