### ISSUE TITLE
[Feature Request] Stream local content to kodi

### ISSUE THREAD

**Issue by ritiek** [xbmc/chorus2#287]
I would love it if it were possible to stream local media files (on different machine other than kodi) through the chorus interface to kodi server.

I made a small [tool](https://github.com/ritiek/play-on-kodi) that implements this feature but I'll be very happy if something like this can be done by chorus web interface itself.

**Comment by jez500** [comment]
The only way to do this is like what you have done, instantiate a server on the device running the browser, create a url and it to kodi. As a web browser does not allow this (without installing node/etc) so it cannot be done.  

I do however plan on adding a "play url" option where you can play anything in kodi that is already on a server (eg youtube, stream url, etc). see #275
