### ISSUE TITLE
Unable to stream/download local medias

### ISSUE THREAD

**Issue by anthony-sticky** [xbmc/chorus2#289]
When I try to download or stream medias located on my osmc Box with a browser i got a blank page.

If i directly try to reach http://osmc_web_server_ip/vfs/ url i get a HTTP 500 error code:

![image](https://user-images.githubusercontent.com/5138633/29002896-2637c31e-7aad-11e7-90fc-93917344f982.png)

Any idea?

**Comment by kikendo** [comment]
I think you are having the same issue as https://github.com/xbmc/chorus2/issues/280

**Comment by jez500** [comment]
Yeah, I think this is a OSMC/Pi issue with Kodi not Chorus

**Comment by kikendo** [comment]
Hey jez500, I recently switched to LibreELEC, tired of OpenELEC being an insecura and not frequently updated garbage, and someone in the forums found a fix for this issue. I put it here for anyone who runs into this to try:
https://forum.libreelec.tv/thread/3431-webserver-local-streaming-playback-http-vfs-401-fix/?postID=26032#post26032

I haven't tested it in OpenELEC but it might also work.
It worked just great in LibreELEC!
