### ISSUE TITLE
Support accessing via /addon/[addon name]

### ISSUE THREAD

**Issue by jez500** [xbmc/chorus2#29]
Investigate jsonrpc path is not root

**Comment by mizaki** [comment]
My changes earlier means this should work. It's also how I always access it. The only way it should try to access /addon/<interface>/jsonrpc is if reverse proxy option is set. Or an older version is used.

I've not tried it with Beta yet but I don't see how that would affect it.

**Comment by jez500** [comment]
I think this still needs more tinkering, the way I see it there is 4 ways it could be accessed

Kodi at root domain
http://IP/
http://IP/addon/webinterface

Kodi not at root domain
http://IP/kodi
http://IP/kodi/addon/webitnerface

This also relates to image paths not jsonrpc.
There is a number of issues on this witch chorus 1
eg 
https://github.com/jez500/chorus/pull/77 
https://github.com/jez500/chorus/pull/78

**Comment by jez500** [comment]
Moving this to #133
