### ISSUE TITLE
nearly invisible IMDB links 

### ISSUE THREAD

**Issue by Etheral** [xbmc/chorus2#290]
not sure if it's just my install but the IMDB links for Movies is really hard to see.
looks to be the colour of .imdbblock is set to white and the background colour the same with a 0.1 alpha.
I'm assuming the background should be a different colour and maybe less transparency. 

suggested change base.css line:61 .imdblink {background: rgba(0,0,0,0.5);}

![2017-08-13 13_34_49-chorus](https://user-images.githubusercontent.com/11221285/29245892-3c8734ea-802c-11e7-98c7-39b5f9d626ca.png)

![image](https://user-images.githubusercontent.com/11221285/29245941-52605a70-802d-11e7-8fae-cb80bfe02694.png)

**Comment by jez500** [comment]
I'll fix with #299
