### ISSUE TITLE
Custom functions for voice interface. 

### ISSUE THREAD

**Issue by BetaStacks** [xbmc/chorus2#291]
I build voice interfaces for websites and would like to build one for this Kodi theme. There is a lot happening in the js file. Can you point be to the location of the functions that allow for controlling playback?

**Comment by jez500** [comment]
The JS is compiled from all the coffee script files which is much more readable.

Maybe start by looking here: https://github.com/xbmc/chorus2/tree/master/src/js/apps/player

**Comment by malard** [comment]
not something that can be progressed with this ticket, so closing
