### ISSUE TITLE
Freeze Raspberry Pi

### ISSUE THREAD

**Issue by drrak** [xbmc/chorus2#292]
_Google translator:_
Sometimes when I listen to a playlist from YouTube (Kodi 17.3) on RPi3, launching the application in a web browser freezes RPi3 (RPi2 too). I can not even use the Putty to restart Raspberry Pi.

**Comment by jez500** [comment]
Can you test another web interface and see if the same thing happens, I cant replicate this

**Comment by drrak** [comment]
Another web interface? Sorry, but I do not understand. Should I check another browser? Anyway, I have a freshly installed Kodi and now I rarely use Chorus2. So far I did not have this problem.

**Comment by malard** [comment]
there is no bug here from the perspective of chorus2, if your device is not powerful enough, get a more powerful device
