### ISSUE TITLE
adjust browser players to be responsive

### ISSUE THREAD

**Issue by StijnDC** [xbmc/chorus2#293]
The VLC web player plugin stopped working for chrome a while ago, so i'm using firefox for video playback.
I currently manualy adjust the HTML/CSS so the video player is bigger and watchable when i split the screen. 
i also noticed that the player is not responsive.
is it possible to adjust this?

**Comment by jez500** [comment]
It should be responsive, the html5 player definitely is?

**Comment by malard** [comment]
i can't see any issue as of 2024
