### ISSUE TITLE
[Feature Request] Ability to Add sources and Add network locations

### ISSUE THREAD

**Issue by beaglenz** [xbmc/chorus2#294]
It would be great to be able to Add sources to the File Manager area in Systems and also Add network locations in the Browse for new shares sections. This would enable speedy setup/maintenance of Kodi.

**Comment by jez500** [comment]
I would love this too, not yet supported by the API though. That said I believe it might be something that will be added at some point soonish

**Comment by gczuczy** [comment]
I just installed my first kodi/osmc. so far wasted 2 hours of my life trying to add an NFS mount to the library.

I have an installation, without the ability to add any files to it, and play them.

Seriously, we are unable to add sources with Chorus2?

I'm really amazed that this needs a feature request, and Chorus2 was released without this.

**Comment by RV999** [comment]
it would be even better if you could install add-on repositories via the web interface.

**Comment by cmasterdelphi** [comment]
I really thought, I was incompetent because I tried this a whole day without success till I found this thread.
I installed an "headless kodi" on an docker and there is no way, that I can use it now. It just sits there on the docker being utterly useless.
