### ISSUE TITLE
Add-on context menu different than kodi on tv....

### ISSUE THREAD

**Issue by DjDiabolik** [xbmc/chorus2#295]
Whit some addo-on i can explore all result (like video files or audio files) also on kodi on tv but also by a PC using chorus webui.

From PC... use for an example the "official" latest Youtube addons..... i can navigate to found a video and on tv i can open a context menu whit various option.
On Chorus2 some option it's not disponible.... i click on 3 dots and the only option it's "Queue in kodi"....

It's normal ? I need to activate some option for showing all voices like appears on tv ?

**Comment by jez500** [comment]
Addons don't expose their context menus to the API, so the web interface can only support the generic (applies to all) options. 

What you can do is: Press `c` to open the context menu on the screen when in the web interface and navigate with the keys

**Comment by malard** [comment]
outside the scope of the web interface
