### ISSUE TITLE
[Feature Request] add the ability in the settings dialog to add a logout button with a custom url string

### ISSUE THREAD

**Issue by tylerhoadley** [xbmc/chorus2#298]
Currently I use Chorus behind a local apache2.4 reverse proxy with auth_mod_openidc and I protect it with Auth0 Oauth2 provider. It works great however, I've had to modify the "kodi-webinterface.js" and the K button url in the top left of chorus to do a proper logout, removing the true '#' function.

As a feature request, could you add the ability in the settings dialog to add a logout button with a custom string to provide this logout function without me having to manually highjack this K button url if and when the next release is installed.

Thanks,

**Comment by jez500** [comment]
Would the ability to add an external link to the side menu solve this? currently you can only add internal links

**Comment by tylerhoadley** [comment]
jez500.

I was thinking something else however after looking at the "Main Menu Structure" page, I see what you mean. Yes this would be ideal with a logout icon.

**Comment by malard** [comment]
this is too niche for general development, please submit a PR
