### ISSUE TITLE
Can't access the interface "file not found"

### ISSUE THREAD

**Issue by zombieagain** [xbmc/chorus2#301]
HI,
I'm using SPMC krypton (alpha 10), but the same problem happens also with standard Kodi. My hardware is NVIDIA Shield TV.
Whenever I try to connect to the web interface at this address:
http://192.168.1.4:8080/addons/webinterface.default/
I get a blank page and the message "file not found"
I installed Chorus just to see that it wasn't a network configuration problem, but Chours works just fine at this address:
http://192.168.1.4:8080/addons/webinterface.chorus/
Any suggestions on where to look?
Thanks!

**Comment by jez500** [comment]
http://192.168.1.4:8080/addons/webinterface.default/ should work but it isn't the best way to access it, if you enable the web interface and set as default just use http://192.168.1.4:8080/

**Comment by zombieagain** [comment]
Thanks! Unfortunately I get the same result: "File not Found". Is there any problem specific to the Shield TV? My setup does not have anything special, I think.

**Comment by jez500** [comment]
Works fine on my shield, make sure you:
* Have followed "Enabling & Configuring" in the readme
* Are using the correct IP/PORT
* Are using Kodi v17+

**Comment by Bogey** [comment]
Same problem here: file not found.

**Comment by billymcintosh** [comment]
`/lang/_strings/en.json 404 (Not Found)` - just get the loading spinner.

**Comment by leeronr** [comment]
Had the same issue and solved it by manually copying the missing directory (`_strings`). 

Grab the source code and copy `xbmc-master/addons/webinterface.default/lang/_strings` to `/YOUR%SYSTEM%USERDATA%PATH/addons/webinterface.default/lang/` (locate your system userdata path [here](http://kodi.wiki/view/Systemdata))
