### ISSUE TITLE
Volume control difficult to detect for newbies

### ISSUE THREAD

**Issue by jondo** [xbmc/chorus2#302]
I have used Chorus2 for the first time today, and it took me a long time to detect the volume control. Finally I found the issue #242, from which I learned the necessary keypad keys, and by changing the volume with these keys I managed to detect the changing volume in the GUI.

To keep the GUI minimal, this could also be described in a 'users guide' (#143).

**Comment by ninovanhooff** [comment]
Also the graphical grey bar above the mute, repeat etc buttons because it's not visually distuingishable from the other elements
![image](https://user-images.githubusercontent.com/10351007/71319968-370ca200-24a5-11ea-8eed-382f380dac2c.png)
