### ISSUE TITLE
Firefox cannot read the pvr timestamps

### ISSUE THREAD

**Issue by ninjafuchs** [xbmc/chorus2#306]
I am a Firefox user and i always had this issue even with the new release (version 57) firefox has trouble to identify the timestamps from the pvr shows. The time is only shown like this: Name of the Show:
nan:anpm - nan:anpm (45min)
undefined, NaNth undefined 
Other browsers don't have this kind of problem. It seems like they are more forgiving when it comes to this issue.
In this link there seems to be a solution. I am not a programmer. I dont know nothing about it. But maybe it helps.
https://stackoverflow.com/questions/16235405/time-show-nannan-in-firefox-chrome-works-perfect

**Comment by ivanllc** [comment]
same problem in Safari, Only work in Chrome base browser.
There is one more problem that it not shows in local time, in UTC?
