### ISSUE TITLE
Chorus doesn't play MKV/ AVI etc...

### ISSUE THREAD

**Issue by HansCie** [xbmc/chorus2#308]
Hello,
I have an issue with Chorus not starting/ recognizing MKV/ AVI files to play in a browser elsewhere in a local network. It does start MP4 files though (playing them nicely). I have openelec on a raspberry pi as a server for these movies. 
I had this setup working until a few weeks ago, but had to rearrange things in the system, so probably this has to do with CODECSes? Or some ADD-ons I did not yet install?
Thanks!
Hans

**Comment by lbrunkho** [comment]
I am still having this issue on libreelec 8.2.5, the only file format that i can play is .mp4, all .mkv files that i play fail. even thought they use the same format, H.245/265 and ACC audio. This seems to strictly be an issue with the file container. Hoping this issue gets resolved soon.

**Comment by petterreinholdtsen** [comment]
I see this too, with Chorus version 18.x-2.4.6.  When I try to play the mkv file in the browser after browsing to the file in the file browser module, the video starts playing on the Kodi server instead of in the web browser.

**Comment by maximeB** [comment]
I faced the same issue, so I dug in and found out it's rather my browser (Firefox ver 88) that doesn't support mkv (or avi) yet supports mp4.
Most recent browser stopped support for VLC plugin (see [vlc doc](https://wiki.videolan.org/Documentation:WebPlugin)) so only HTML5 playback is available, yet there is no standard in HTML5 for supported container.

The good news is Chrome based browsers seem to be supporting mkv (I personally tried it with Microsoft Edge).
As for Firefox, there is an open bug to add support for mkv [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1422891)

**Comment by slmingol** [comment]
Been investigating this issue a bit as well. Can confirm that I cannot play the following video format through Chorus 2:

```
Video: HEVC 720P (1280 X 720)
Audio: AAC 2.1 (ENGLISH)
```

I'm on version of Kodi that comes with LibreELEC:

```
Distribution: LibreELEC (official)
Version: 9.0.2
Architecture: Odroid_C2.arm
```

Whenever I attempt to stream an HEVC video it just shows black in my browser:
```
Chrome Version 91.0.4472.77 (Official Build) (x86_64)
```

I'm on MacOS Catalina 10.15.7. But have similar versions on a Windows 7 laptop and it doesn't work there either. I can download the videos and play them fine in VLC and I can play them fine on the LibreELEC Odroid box as well.

**Comment by malard** [comment]
this isn't a chorus2 defect but rather the browsers support for these file containers
