### ISSUE TITLE
Searching for more images goes on indefinitely

### ISSUE THREAD

**Issue by devster31** [xbmc/chorus2#309]
When trying to change the poster or the background images the page just keeps on loading forever without showing any new images.
Here a screenshot of the issue.
![https://snag.gy/yA60nE.jpg](https://snag.gy/yA60nE.jpg)
Which information are needed to debug this?

**Comment by planet** [comment]
i see the same issue

**Comment by LubikR** [comment]
It seems that the problem is old TMDB API key - fixed in #313

**Comment by devster31** [comment]
I changed the key manually and it seems to work.

**Comment by devster31** [comment]
Is there any news about having this in master?

**Comment by jez500** [comment]
Fixed default key, and you can add your own API keys via settings if you want
https://github.com/xbmc/chorus2/releases/tag/17.x-2.4.5
