### ISSUE TITLE
Not possible to see movies mounted from external disk on rapsberry - osmc

### ISSUE THREAD

**Issue by cmoulliard** [xbmc/chorus2#314]
Hi,

I'm running osmc (2017.12-1) on raspberry pi 3 box where my movies are mounted as a volume from an external disk. When I use yatse remote controler from android mobile, I can select under "movies" the external disk mounted and next a movie. 

But if I use chorus2 and access the web http server at the address 192.168.1.20:8080, then the list of the movies is empty

<img width="901" alt="screenshot 2018-01-20 15 34 55" src="https://user-images.githubusercontent.com/463790/35184688-30d9a038-fdf9-11e7-93fb-0e6f40306970.png">

Is there a trick to select from the Web UI, the movies from an external disk ?

Regards

Charles

**Comment by arbego** [comment]
You have to explicitly add your external disk as source and populate your movies by selecting this source. See here: https://yatse.tv/redmine/projects/yatse/knowledgebase/articles/6#Kodi-security
