### ISSUE TITLE
Option to disable Kodi player entirely

### ISSUE THREAD

**Issue by csculley** [xbmc/chorus2#318]
Even with the "Allow Remote Control from applications on this system" option disabled in the native Kodi settings, Chorus2 can still play and control media playing on the native kodi application. An option to disable the Kodi player tab and context options (just leaving the web local player) would prevent this entirely. For full effectiveness, this would probably implement some type of central storage for web settings proposed in #272.

**Comment by malard** [comment]
dupe/same as #384
