### ISSUE TITLE
Browser does not returns all files (API: Files.GetDirectory)

### ISSUE THREAD

**Issue by JosefRypacek** [xbmc/chorus2#322]
I've started using Kodi (17.6 Git:20171115-d69a54a) and I found that scrapper is not perfect and some movies aren't indexed, so I'm sometimes browsing movies by folders (GUI on TV). It works fine and there are indexed and not indexed movies in my folder hierarchy.

Chorus2 (2.4.4) has browser too, but it's functionality is somehow broken... There are missing folders and movies when movies are indexed. Please see example below.
I'm not sure if the shouldn't be fixed in kodi.

### prepare test environment
`cd /nfs/path` // this path is added as movie library in Kodi
`mkdir d`
`touch d/Despicable Me (2010).avi`
`touch d/Despicable Me 2 (2013).mkv`
`touch d/Despicable Me 3 (2017).mkv`

### query used to test browser behaviour
`curl 'http://ip:8080/jsonrpc?FileCollection' -H 'Content-Type: application/json; charset=UTF-8' --data-binary '{"jsonrpc":"2.0","method":"Files.GetDirectory","id":"123","params":{"directory":"nfs://nfs/path/","media":"video"}}'`

and the second one with "directory":"nfs://nfs/path/d"

### OK: response when using "Local Information Only" (movies are not indexed)
`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/","filetype":"directory","label":"d","type":"unknown"}],"limits":{"end":1,"start":0,"total":1}}}`

`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me (2010).avi","filetype":"file","label":"Despicable Me (2010).avi","type":"unknown"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 3 (2017).mkv","filetype":"file","label":"Despicable Me 3 (2017).mkv","type":"unknown"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 2 (2013).mkv","filetype":"file","label":"Despicable Me 2 (2013).mkv","type":"unknown"}],"limits":{"end":3,"start":0,"total":3}}}`

### KO: response when using "The Movie Database" (movies are indexed)
`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me (2010).avi","filetype":"file","id":540,"label":"Despicable Me","type":"movie"}],"limits":{"end":1,"start":0,"total":1}}}`

There is missing folder d and there is only 1 movie from 3 available, so behavior is totally weird.

`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me (2010).avi","filetype":"file","id":540,"label":"Despicable Me","type":"movie"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 3 (2017).mkv","filetype":"file","id":542,"label":"Despicable Me 3","type":"movie"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 2 (2013).mkv","filetype":"file","id":541,"label":"Despicable Me 2","type":"movie"}],"limits":{"end":3,"start":0,"total":3}}}`

### OK: response when "media":"video" changed to "media":"files"
`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/","filetype":"directory","label":"d","type":"unknown"}],"limits":{"end":1,"start":0,"total":1}}}`

`{"id":"123","jsonrpc":"2.0","result":{"files":[{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me (2010).avi","filetype":"file","label":"Despicable Me (2010).avi","type":"unknown"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 3 (2017).mkv","filetype":"file","label":"Despicable Me 3 (2017).mkv","type":"unknown"},{"file":"nfs://10.11.12.2/verejne/filmy/d/Despicable Me 2 (2013).mkv","filetype":"file","label":"Despicable Me 2 (2013).mkv","type":"unknown"}],"limits":{"end":3,"start":0,"total":3}}}`

This is working fine, but this probably can't be used to load images and other information about movies which are indexed...

**Comment by malard** [comment]
nothing in this case relates to chorus2
