### ISSUE TITLE
v18/Leia: Music > Song browsing is broken (songs and album details not listed) in Chorus2

### ISSUE THREAD

**Issue by arigit** [xbmc/chorus2#327]
Tested with the latest v18 nightly (alpha2)

Via Kodi GUI, I am able to browse my Music collection with no issues (by Genre, Album, Songs etc) and play it back.

Via the Web Interface (Chorus2), Albums and Genres are listed as usual, as well as artists. However, when clicking in any album (which would normally display), no songs are displayed.

Forum discussion thread with details, including debug logs: https://forum.kodi.tv/showthread.php?tid=333140

I reported this initially in the Music team but they diagnosed immediately that the problem is with Chorus2 using an outdated JSON API.

Sample error triggered by Chorus2 when I try to browse the contents of an album:

> 15:12:25.922 T:140249047422720   DEBUG: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"AudioLibrary.GetAlbumDetails","id":"1529781145889","params":{"albumid":3889,"properties":["thumbnail","playcount","artistid","artist","genre","albumlabel","year","dateadded","style","fanart","mood","description","genreid","rating","type","theme"]}}
> 15:12:25.922 T:140249047422720   DEBUG: JSONRPC: Value does not match any of the enum values in type
> 15:12:25.922 T:140249047422720   DEBUG: JSONRPC: Array element at index 12 does not match in type properties

**Comment by mrobe** [comment]
I am having problems with this too. I am willing to try and help resolve it, but I need guidance setting up the build environment. Anybody?

**Comment by jez500** [comment]
Hi All,  I know this is an issue and is very high on my priority list.

As the API has changed between 17 & 18 I need to update any pending PRs and do a final release for 17, then fork a version for 18 where dev/fixes can be applied to Leia only

Will likely have 2 new branches going forward, something like...
`17.x-dev` & `18.x-dev`

**Comment by mrobe** [comment]
Sounds great, thanks! What can we do to help?

**Comment by jez500** [comment]
Should be all fixed now :)
To test install the zip from this release https://github.com/xbmc/chorus2/releases/tag/18.x-2.4.5

**Comment by mrobe** [comment]
Thanks!

How do we install this?

My failed attempt is described here: 

https://forum.kodi.tv/showthread.php?tid=333520&pid=2754879#pid2754879

**Comment by jez500** [comment]
* Extract the zip, eg to your desktop, it should be one folder `webinterface.default`
* Find that same folder in your Kodi install, eg on windows it might be `C:\Program Files (x86)\Kodi\addons\webinterface.default`
* Delete the `webinterface.default` folder inside your Kodi install addons folder
* Copy the extracted `webinterface.default` folder to the addons folder

**Comment by mrobe** [comment]
Linux machine. I just tried it again. Rebooted. **Help > About Chorus** still says 2.4.4.

**Comment by arigit** [comment]
@mrobe the latest kodi nightlies already come with chorus 2.4.5 included, so just install a recent nightly - the issue is fixed

**Comment by mrobe** [comment]
Thanks! Got it sorted. The very stubborn Safari cache was throwing me off.

Now wondering about this: https://github.com/xbmc/chorus2/issues/331
