### ISSUE TITLE
Document the Development process

### ISSUE THREAD

**Issue by mrobe** [xbmc/chorus2#331]
I would like to get involved with Chorus, but I'm stuck on setting up a development environment and what the development process looks like. The notes in the readme are pitched at too high a level for me.

Maybe some more detailed instructions on this (suitable for the noob-ish) could be added to a new readme?

Let's say I have Ubuntu Server 18.04 running Kodi v18 and Chorus2. What do I do?

**Comment by jez500** [comment]
Hey @mrobe I will try and wrap the dev environment into a docker container which should remove any issues with installing dependencies and getting things up and running. I'll combine that with some general how-to docs. You will need some experience with [coffeescript ](https://coffeescript.org/) as that is what the source is written in

**Comment by mrobe** [comment]
Would it be possible to document a basic dev approach that doesn't involve docker? I've never used that and the documentation on their web site doesn't seem very clear to me.

**Comment by jez500** [comment]
Docker is a lot less complicated than setting up all the dependencies manually. You just install docker and type `docker run` and you have a perfect dev environment ready to go, you don't really need to know more than that one command

**Comment by mrobe** [comment]
I understand that's the idea, but when I looked at their docs for Ubuntu, my eyes started to glaze over. There is no mention of Ubuntu Server vs. Desktop (I'm using Server), no mention of the install procedure on Ubuntu 18.04, a bunch of other nomenclature that makes no sense to me, etc. Docker itself looks like another dependency that I'll have to worry about.

**Comment by bjornfor** [comment]
And if you *really* don't want to use docker, the Dockerfile is easy to read and you can do each of its steps manually in your Ubuntu.

**Comment by mrobe** [comment]
Thanks for this. Tbh, I wouldn't even know where to look for "the dockerfile". The basic issue here is knowledge and learning curve. I'm not opposed to docker in principle. It's just that I don't have the time to go off and try to wrap my head around a bunch of complicated tools. Clearly, I'm not alone, either. 

Look at the Chorus forum. It was dead stuck for months on some v18 compatibility bugs until jez500 came and thankfully bailed us out. People were posting questions like "Is Chorus dead?" Etc.

Don't get me wrong. I understand this is freeware and people have other projects, paying jobs, etc. Me too. It's just that the same thing is going to happen again, unless the bar is lowered for less expert developers to get involved. As it stands now, modifying the Chorus code requires a bunch of specialized knowledge about tools, development process, and possibly the internal design of Chorus (which AFAICT isn't documented either). It looks to me like nobody on the Chorus forum for at least the last 4-6 months has any of this knowledge, as questions were going unanswered, threads with zero replies, there were no check-ins on the repository for over a year, etc.

If somebody who really understands Chorus can lower the bar, maybe more people could get involved. More specifically, I'd suggest documentation that clearly explains all the steps to set up the build environment, the steps to modify Chorus, more details on its design, etc. Assume a noob audience.

I am willing to help get the documentation in shape, but again, I'm pretty much a noob.

Sorry for this long post. I've just seen too many perfectly good software packages die because they were never documented, the developers got busy, moved on, version compatibility issues appeared, etc. I hope you understand this concern.

**Comment by jez500** [comment]
Hey @mrobe 

Developer docs added https://github.com/xbmc/chorus2/blob/master/src/lang/en/developers.md 

All you need to do is install docker and run a couple of commands and you are on your way to compiling/testing/contributing to chorus! 

As I mentioned before, it is a complex app, so there is a fair amount of knowledge you require, but this should definitely get people past the first stumbling block

And if you really don't want to use docker, as @bjornfor mentioned, the commands used to build the docker image can be found here https://github.com/xbmc/chorus2/blob/master/Dockerfile
