### ISSUE TITLE
Chrome net::ERR_CONNECTION_REFUSED on POST requests

### ISSUE THREAD

**Issue by threesquared** [xbmc/chorus2#334]
I am encountering a strange issue with the Chorus 2 interface. I am using the [lsioarmhf/kodi-headless:latest](https://github.com/linuxserver/docker-transmission-armhf) docker container and am able to access most the web interface fine. 

However certain jsonrpc connections seem to result in a cryptic `net::ERR_CONNECTION_REFUSED` error in chrome with no response from the server as headers or content. This happens on the movies and tv episode pages.

![image](https://user-images.githubusercontent.com/892142/43482784-95f3a226-9501-11e8-896c-3e715eecd454.png)

I have observed this happening mostly with the following calls:

* /jsonrpc?TVShowCollection
* /jsonrpc?MovieCollection

When trying the request in Postman I get the following error:

![image](https://user-images.githubusercontent.com/892142/43482996-3786d784-9502-11e8-9a55-02b617e311b8.png)

But a GETrequest to the same endpoint results in a response.

![image](https://user-images.githubusercontent.com/892142/43483038-548c131c-9502-11e8-9a36-11a3b695dd4e.png)

Even more confusing is that these requests appear in the kodi log?

```
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]: request received for /jsonrpc?TVShowCollection
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] HTTP/1.1 POST /jsonrpc?TVShowCollection
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Query arguments: TVShowCollection =
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Accept: */*
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Authorization: Basic a29kaTprb2Rp
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Connection: keep-alive
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Content-Type: application/json
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Host: 192.168.0.10:8082
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] Postman-Token: e6515e8a-ae03-4d85-b53c-56eec9fdca45
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] User-Agent: PostmanRuntime/7.2.0
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] accept-encoding: gzip, deflate
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] cache-control: no-cache
19:46:26.934 T:4066374624   DEBUG: CWebServer[8082]  [IN] content-length: 326
19:46:26.934 T:4066374624   DEBUG: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"VideoLibrary.GetTVShows","id":"1533064961011","params":{"properties":["title","thumbnail","playcount","lastp
layed","dateadded","episode","rating","year","file","genre","watchedepisodes","cast","studio","mpaa"],"limits":{"start":0},"sort":{"method":"title","order":"ascending","ignorearticle":true}}}
19:46:26.946 T:4066374624   DEBUG: RunQuery took 3 ms for 136 items query: SELECT * FROM tvshow_view
```

Any ideas on what could be preventing these POST requests?

**Comment by malard** [comment]
whatever it is, it will be local to you
