### ISSUE TITLE
Chorus 2.4.5 displays TV shows that have been deleted and no longer show in Kodi library

### ISSUE THREAD

**Issue by xXcodgerXx** [xbmc/chorus2#336]
Hello,

After removing some TV Shows, cleaning then updating the library, I noticed Chorus still displays these shows. I tried refreshing the page and even using a browser that has never connected to Kodi and the deleted still appear. This does not happen with Movies. 

Removing the TV Show source cleaning the library, then re adding the source and updating the library fixes it.

**Comment by xXcodgerXx** [comment]
On a fresh Win 10 x64 install with all updates and all content on a local drive, latest Beta 5 Chorus 2.4.6 still has the same problem. The problem started happening around the same time when the nightlies - Chorus stopped allowing the option to clean the library. 

Are there any logs I could provide that might help?

**Comment by malard** [comment]
Chorus2 only displays the data from the JSONRPC so this would be a bug in Kodi's datastore rather than the web interface
