### ISSUE TITLE
Show custom addon in Web Interface

### ISSUE THREAD

**Issue by fatcatsanonymous** [xbmc/chorus2#339]
Hi, I am triggering a custom addon which opens an overlay from the main menu (/addon/execute/script...) This is working in that it opens the overlay on the kodi interface when I execute the addon from the chorus2 menu, but the overlay is not visible on the web interface. 
Rather than linking to the addons page when I execute the addon, I would like to see the overlay open over the "page" I'm on, i.e. music or video etc. Is this possible? Thanks for any hint as to how I might achieve this.

**Comment by malard** [comment]
the web interface is for controlling official addons and kodi natively. Third party addons would need to extend and support their own web interface
