### ISSUE TITLE
Update packages used

### ISSUE THREAD

**Issue by razzeee** [xbmc/chorus2#345]
### Describe the bug
Here is a clear and concise description of what the problem is:

We need to update the dependencies to close various security problems in those.

## Possible Fix

Update package.json and package-lock.json

**Comment by malard** [comment]
with a lack of specificity on the actual packages that need to be updated I am closing this ticket.

**Comment by razzeee** [comment]
Well at this point every package :D

Running `npm audit` might also help, but I suspect, that upgrading packages will break and cause more work, with the last update being 5 years old.

**Comment by malard** [comment]
if you want to do file a proper bug report with a reason why the update needs to be done I will consider it and the associated effort. But to simply say update packages without giving a reason other than "security reasons" leads to me to feel this is just effort for efforts sake
