### ISSUE TITLE
Latest Chorus2 on Kodi 18b4 not able to download thumbnails

### ISSUE THREAD

**Issue by kbirger** [xbmc/chorus2#347]
## Expected Behavior

- Load Chorus2 UI
- Click on Movies or TV shows
- Get a grid of Movies or TV shows
- Thumbnails load

## Actual Behavior
Thumbnails do not load. The grid is full of empty squares, and I have 404 errors in my dev tools network log

>http://192.168.1.105:8084/image/image%3A%2F%2F%252fstorage%252fNSA325%252fvideo%252fmovies%252fXXXXXXXXXXXX%252fFILE-poster.jpg%2

### Debuglog

The debuglog can be found here:

### Your Environment
Used Operating system:

 - Used browser(s): Chrome
 - Operating system version/name: Win 10
 - Kodi version and platform: v18b3 Nvidia shield
 - Chorus2 version: 2.4.5
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
See xbmc/xbmc#14726
