### ISSUE TITLE
Control volume

### ISSUE THREAD

**Issue by TimerWolf** [xbmc/chorus2#349]
Control volume

Why is there no option direct in the web interface to turn the volume down or up? I have not found it anywhere and it seems to be the most important thing that is missing, i know you can do it whit the keyboard whit + and - but i don´t have those on my keyboard and how would you do that in a mobile phone? Seems to be nice if you could do it manually as well.

### Context
Does this really need to be stated? I would say its and standard feature that should have been there from the start,,,,

### Possible Implementation
You can mute the sound, so many if you hover over it it shows the volume from 1/100% and you can click ether on the top or button to get 1% or 100%

**Comment by antonstarlid** [comment]
I use it in the mobile and not desktop.......

\ Lukasz

Den sön 6 jan. 2019 20:26 skrev Russell <notifications@github.com>:

**Comment by Rusty77** [comment]
Ok, i don't.  But I've just found it on my Android, if start a song, and tap on the playing track icon, bottom-left, then the same volume slider appears immediately above the mute button on the 'controls' view.

**Comment by antonstarlid** [comment]
I need to check that out, thanks!

Den sön 6 jan. 2019 20:34 skrev Russell <notifications@github.com>:

**Comment by Nautigsam** [comment]
This volume slider is a perfect example of bad UX. I discovered it by accident. There is no text indicating that it is meant to control the volume, no tooltip, nothing.
