### ISSUE TITLE
Request - Flac support

### ISSUE THREAD

**Issue by jez500** [xbmc/chorus2#35]
Currently using [Sound Manager 2](http://www.schillmania.com/projects/soundmanager2/), it ticks all the boxes except for flac support.

Changing local players 'should' be possible by changing only the [local controller base](https://github.com/jez500/chorus2/blob/master/src/js/apps/command/local/_base/_base.js.coffee) and [audio stream init](https://github.com/jez500/chorus2/blob/master/src/js/apps/audioStream/init.js.coffee). Functionality might be lost with a switch so maybe have a setting where you can local toggle players.

Need to test [Aurora.js](https://github.com/audiocogs/aurora.js) with [flac.js](https://github.com/audiocogs/flac.js). Demo played a flac ok in chrome.  No IE support mentioned but who really cares about that.

**Comment by zag2me** [comment]
This would be very nice! Everyone uses Chrome anyway ;)

**Comment by xochipilli** [comment]
With this implemented I could finally stream all my library!

**Comment by StephRun** [comment]
FLAC on local ?   YEESSSSSS !  Please!!!!!!    :) GO! GO! GO!  ;)

**Comment by bendschs** [comment]
hey, is there a ETA for this feature?

cheers bendsch

**Comment by microcreators** [comment]
Hi there... Chorus2 is lovely, much better design than v1. Still... Can't stream flac files locally. Any chance?
Yes, I can donate beer. 👍

**Comment by solarist** [comment]
Google Chrome version 56 is the first version to support FLAC streaming via the HTML5 <audio> tag. Current Canary version supports it already.

https://bugs.chromium.org/p/chromium/issues/detail?id=93887

**Comment by jez500** [comment]
Great news @solarist - thanks!
I'll be testing that out soon and do all I can to get it working in Chorus

**Comment by jez500** [comment]
Just tested, no changes to Chorus were required, FLAC now just works, awesome!
As @solarist mentioned you just need Chrome version 56 or greater, [grab Canary](https://www.google.com.au/chrome/browser/canary.html) if you don't want to wait for stable Chrome to catch up.

**Comment by StephRun** [comment]
IT WORKS !!!!
Fantastic ! Thanks to all !!!

De : jez500 <notifications@github.com>
Répondre à : xbmc/chorus2 <reply@reply.github.com>
Date : vendredi 16 décembre 2016 09:00
À : xbmc/chorus2 <chorus2@noreply.github.com>
Cc : Stéphane DENIS <stephane_denis@hotmail.com>, Comment <comment@noreply.github.com>
Objet : Re: [xbmc/chorus2] Request - Flac support (#35)


Just tested, no changes to Chorus were required, FLAC now just works, awesome!
As @solarist<https://github.com/solarist> mentioned you just need Chrome version 56 or greater, grab Canary<https://www.google.com.au/chrome/browser/canary.html> if you don't want to wait for stable Chrome to catch up.

**Comment by Jeroonk** [comment]
I can also confirm that FLAC works natively in Chorus2 on Firefox 51.0 beta (due to release Jan 2017) which brings FLAC support to Firefox as well: [51.0 Beta Releasenotes](https://www.mozilla.org/en-US/firefox/51.0beta/releasenotes/). Seems like this issue will solve itself as browsers adopt FLAC support.
