### ISSUE TITLE
Collaborative playlist selection: Enhancement suggestion

### ISSUE THREAD

**Issue by lhrmota** [xbmc/chorus2#351]
I hope this is the right place to place suggestions, in this case a feature request.

I'd like to have Kodi as the media centre for parties, playing songs and/or videos. It would be nice to let the audience see the playlist and select or down and upvote items on the playlist, using their phones.

I think this kind of behaviour was provided by a Linux application that is no longer available: https://seelio.com/w/1n5/udj . This solution, however, required user registration and needed an app to be installed on the phone. I'd like to have a local solution, provided through a web page, to allow all phones to connect, with no requirement on registration, os or app installation.

**Comment by malard** [comment]
too niche for general development, happy to accept a PR

**Comment by lhrmota** [comment]
I may be offering this feature as a Master thesis these coming months... If it runs well, I'll report when possible.
