### ISSUE TITLE
Not Add Source in the Web Interface

### ISSUE THREAD

**Issue by thebravoman** [xbmc/chorus2#352]
### Describe the bug

I've installed and enabled the web interface of kodi. I do not have a monitor so web interface and ssh access is the only thing I have. 

When opening the web interface I can not add music sources. The web interface seems to be missing a lot a lot of things are probably not loaded.

I could provide a screenshot - https://robopartans.com/mkirilov/kodi-web-interface-error.png

## Expected Behavior
I would like to have and Add Source button in the web interface

## Actual Behavior
I do not have an Add Source button

### To Reproduce
On a raspberry
sudo apt-get install kodi 

Then follow https://kodi.wiki/view/Web_interface to enable web interface by creating  advancedsettings.xml. 

Then go to web interface
### Debuglog
I would like to attach one but every time when I enable  "Enable debug logging" in the web interface and click save and restart kodi, the "Enable debug logging" is still disabled. So I can not even save from the web interface.
 
### Screenshots 
I could provide a screenshot - https://robopartans.com/mkirilov/kodi-web-interface-error.png

### Your Environment
Used Operating system:
 - Used browser(s): Fireforx and Chromium
 - Operating system version/name: Ubuntu 18.04
 - Kodi version and platform:17.6
 - Chorus2 version: How could I found this?

**Comment by MartijnKaijser** [comment]
This is simply not possible because it's missing in the JSON RPC interface from Kodi itself and has to be added there first
