### ISSUE TITLE
incorrect sorting of albums under artist

### ISSUE THREAD

**Issue by hetzalwel** [xbmc/chorus2#354]
It seems to generate list of albums beloinging to one artist at random.
Not on date / not on albumsort / not on alphabet.
Tags are ok. Kodi (18.0) itself does ok.

also year is displayed incorrect:
Conspiracy [remaster +2]
<a href="#music/albums?year=1989">1

  _a href="#music/albums?year=1989"_1
_ should be < or >, but otherwise it's not visible.

**Comment by arigit** [comment]
Possibly related to (same root cause as) #358
