### ISSUE TITLE
Love to have: Simple HTML status page

### ISSUE THREAD

**Issue by dieladuese** [xbmc/chorus2#355]
## Feature suggestion
**Detailed Description**

I am using Kodi on a HTPC which has a frontpanel display (VFD) controlled by LCDHype. LCDHype can accquire informations from web services and print them on the frontpanel display. This is quite flexible as long as the HTML page is quite simple. One has only to write a LCDHype script to read the HTML content and send it to the display. So for example LCDHype can read status from DVBViewer Recording Service, like name of currently recorded TV movie.

I wish, if Kodi could automatically maintain such a website like on <ipadress>:8080/status where it displays in realtime line by line the current task it does, like in which menu the user currently navigates, type of media it plays (TV, DVD, movie, music, ...) current song name / album / band name/ video namem it plays, TV programme name, TV channel name, start time, length, end time, play, pause, next, previous, timeshift, ... 

please keep the page simple that it is not too hard to make script in LCDhype. Maybe also other tools can profit from that,    

### Context

LCDHype can display that information on VGD in the frontpanel of my HTPC

Others are using LCDHype as well. We can share the LCDHype script code to read the Kodi-Chorus-realtime-status page. Maybe also other tools can profit from that.

### Possible Implementation

Keep the page simple, maybe one information per line. 

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
Feel free to create your own addon for this, but this is so specific to this app for a specific use case that is outside the scope of chorus2
