### ISSUE TITLE
Touchscreen axis Y

### ISSUE THREAD

**Issue by JLNapo** [xbmc/chorus2#356]
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Used browser(s):
 - Operating system version/name:
 - Kodi version and platform:
 - Chorus2 version:
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by JLNapo** [comment]
Hello,
I have a 7 "resistive touch screen and the default settings are not correct, I have been able to modify the" advancedsettings.xml "file for the screen surface, but I can not reverse the axis Y that is on the back of the screen My screen has not been inverted in "config.txt" so I do not understand why Y is reversed There are missing parameters in "advancedsettings" or I do not know them not (not found on the internet) Thank you for helping me and surely help other users, thank you for everything you do.
Regards

**Comment by malard** [comment]
this has nothing to do with chorus2
