### ISSUE TITLE
Chorus jumps back to top of "now playing" queue all the time, making removing items tedious

### ISSUE THREAD

**Issue by axelsimon** [xbmc/chorus2#357]
### Describe the bug
I added the same album to the "now playing" queue twice, by mistake. I thought I would just remove the songs added to the queue by clicking the X next to each song in the Audio queue, to the right of Chorus.

Unfortunately, after clicking on the X to delete a song, Chorus brings the focus back to the top of the queue, forcing me to scroll back down after each deletion. This makes deleting multiple items time consuming and annoying.

I don't think Chorus always brings back the focus to the beginning of the queue, but even after a reload of the page, it still does right now.

## Expected Behaviour
- scroll to wherever you want in the queue
- delete an item by clicking the red X next to it
- item disappears, view doesn't move

## Actual Behaviour
- view / focus returns to the top of the queue

### Debuglog
I was not able to get a debug log as debug logging was disable and Kodi became non-responsive not long after I enabled it.

### Your Environment
Used Operating system:

 - Used browser(s): Firefox 66.0.1
 - Operating system version/name: Fedora 29
 - Kodi version and platform: Kodi 18.2 on OSMC 2019.04-1
 - Chorus2 version: 18.x-2.4.6

**Comment by malard** [comment]
the current design of chorus2 does not support ajax like manipulation of the DOM
