### ISSUE TITLE
Album listing display issue

### ISSUE THREAD

**Issue by arigit** [xbmc/chorus2#358]
### Describe the bug

There is a display issue on album listings - in general, the issue is visible every time where multiple albums are listed, for example when listing all albums of a given artist or given year or given genre etc.

In the listing, for each album entry, the album cover is shown and below it the album name, and (before this bug) the album year is shown.

Instead of the album year, the following is shown (example):

![image](https://user-images.githubusercontent.com/652673/56844290-dc6e6800-687b-11e9-8e03-93da3096cf09.png)

i.e. instead of 2006, the following string shows: 

`<a href="#music/albums?year=2006">2006</a>`

I noticed this bug in **Kodi 18.2**; this bug was definitely not present in Kodi 17.6
Reproducible with Firefox and Chrome (details below)

## Expected Behavior
Instead of the HTML code, the year should be shown (2006 in the example)

## Actual Behavior
see image above showing the problem.

### To Reproduce
1. In chorus 2, open the Music section
2. Then click on Artists, then click on any artists
3. All artist albums are shown, and below each album art/cover image and album name, the weird HTML string is shown, instead of the Album Year

### Your Environment
Used Operating system:

 - Used browser(s): Firefox 66.0; Chrome 63.0
 - Operating system version/name: Raspbian / OSMC (19.04)
 - Kodi version and platform: 18.2
 - Chorus2 version: **18.x-2.4.6**
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by Laurent-1971** [comment]
This issue is still there with 18.4

**Comment by t-e-d-d-y** [comment]
Same issue, Chorus2 version: 18.x-2.4.6

**Note**: with firefox inspector we can see some **`&lt;`** and **`&gt;`**

![Capture d’écran du 2019-11-01 00-18-36](https://user-images.githubusercontent.com/57239192/67992514-5b829580-fc3d-11e9-9b2b-54e96d696def.png)

**Comment by arigit** [comment]
PR with the fix merged
