### ISSUE TITLE
[Improvement] Listing of songs in a album grow selection on mouseover.

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#36]
Would be extra nice if when you click on an album and when on mouseover the play, thumbs up and add to queue buttons grew slightly (same as in the active queue)

This would make it easy to see on higher resolution especially when you want to add a song to queue the dammed icons are so tiny.
Examples 
![capture](https://cloud.githubusercontent.com/assets/3521959/8744242/8bb94bda-2c6d-11e5-9ad6-e8942315e85b.PNG)

![capture](https://cloud.githubusercontent.com/assets/3521959/8744279/d569ceee-2c6d-11e5-8ab1-3f315f804ccc.PNG)

also in this view only would benefit from a alternating bg style per song.

![icjmj](https://cloud.githubusercontent.com/assets/3521959/8744484/653bc120-2c6f-11e5-9f6f-2e756d977c85.jpg)

**Comment by jez500** [comment]
not doing this one, works well as is
