### ISSUE TITLE
Single file album is not navigating through songs instead plays album from beginning

### ISSUE THREAD

**Issue by mxilievski** [xbmc/chorus2#362]
### Describe the bug
I have an album that is placed in a single .flac file. This album is separated by songs in Kodi(using metadata file) and it looks like every other music album in Kodi. 
![image](https://user-images.githubusercontent.com/2308950/58416871-4ba9c880-8083-11e9-8ad7-13b2f141fe49.png)

But when I press play on the second song, instead of the selected song it starts playing the first song but on UI it says that it plays the second song. 
![image](https://user-images.githubusercontent.com/2308950/58416890-595f4e00-8083-11e9-9b18-350182fb279e.png)

## Expected Behavior
I expect that when I press play on the second song, the second song should be played instead of starting the whole album from the beginning.

## Actual Behavior
When I press play on second song, it starts playing the first song (starting the whole album from the beginning)

### To Reproduce
1. Download any .flac album in a single flac file (make sure you have metadata so Kodi will know all the songs, start, end times, etc.)
2. Add album to Kodi
3. Open Music in Chorus2, try to play the second/third song

### Your Environment
Used Operating system:

 - Used browser(s): Chrome 74.0.3729.157 / Firefox 67.0 (64-bit)
 - Operating system version/name: Ubuntu 19.04
 - Kodi version and platform: Kodi 18.2 / Ubuntu 18.10
 - Chorus2 version: 67.0 (64-bit)
 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
do you have an example file for me to use to debug this?

**Comment by mxilievski** [comment]
I’m sorry, haven’t used Kodi in years. Feel free to close this ticket.
