### ISSUE TITLE
I made the Japanese translation but Kodi v18.3 doesn't show Japanese items.

### ISSUE THREAD

**Issue by yohru** [xbmc/chorus2#368]
I completed the Japanese translation and executed it locally to check for translation errors,
but Kodi v18.3 does not show "Settings -> language" Japanese items.

![Snap20](https://user-images.githubusercontent.com/16573613/60764287-e86b7700-a0c1-11e9-9dff-b4ddf92606ae.png)

I tried the following.

>The LANG_CODE is the two letter code for that language.

ja

>src/lang/_strings/LANG_CODE.po

File name ja.po
Use application Poedit v2.2.3
Sample in file:

msgctxt ""
msgid "Nothing playing"
msgstr "プレイリストなし"

>Adding a new language

LANG_KEY of ja

>Tell the app about it

translate.js.coffee
Additional item -> ja: "Japanese"

  {
    en: "English"
    cs: "Czech"
    de: "German"
    es: "Spanish"
    fr: "French"
    hu: "Hungarian"
    lt: "Lithuanian"
    nl: "Dutch"
    pl: "Polish"
    pt: "Portuguese"
    zh_hans: "Chinese, Simplified"
    ja: "Japanese"
  }

>src/lang/LANG_CODE/PAGE.md

Additional folder name ja
Added file keybind-readme.md
Sample in file:

キーバインド
Kodiをキーボードで操作できます。これは、デフォルトの設定ですが、[設定のページ](#settings/web)

>Testing
>Ensure nodejs, npm are installed

ok

>cd /chorus/folder

ok -> chorus2-master on desktop.

>npm install (only the first time)

ok

>grunt lang (this will rebuild only the languages in the dist/lang folder)

In my case, I needed "npm install grunt".
The result of grunt is without errors.

In dist folder
chorus2-master\dist\lang\_strings\ja.json
As a result of comparison, there were no errors in the internal structure in the same way as English and other languages.

chorus2-master\dist\lang\ja\keybind-readme.html
keybind-readme.html is confirmed by browser ok.

>Refresh Chorus

All files in chorus2-master\dist folder overwrite C:\Program Files\Kodi\addons\webinterface.default
I accessed Kodi v18.3 with a browser(waterfox,firefox,chrome),but there is no Japanese language setting items.

**Comment by yohru** [comment]
Was self resolved.

C:\Program Files\Kodi\addons\webinterface.default\js\kodi-webinterface.js

>helpers.translate = {};
>helpers.translate.getLanguages = function() {
>  return {
>    en: "English",
>    cs: "Czech",
>    de: "German",
>    es: "Spanish",
>    fr: "French",
>    hu: "Hungarian",
>    lt: "Lithuanian",
>    nl: "Dutch",
>    pl: "Polish",
>    pt: "Portuguese",
>    zh_hans: "Chinese, Simplified",
>    ja: "Japanese"
>  };
>};

Solved by adding ⇒ ja: "Japanese"

**Comment by KarellenX** [comment]
Great!! I will close the issue.
