### ISSUE TITLE
Bug or feature? Album/song listing per artist view doesnt align

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#37]
I tried showing 3 albums for more effect.

![capture](https://cloud.githubusercontent.com/assets/3521959/8744332/4b53dd20-2c6e-11e5-8564-8c7615ea0109.PNG)

If the idea is on purpose so as to avoid confusing which songs belongs to what albums, why not use styles like evrery other Album entry with songs which belong to that album) is shown in a different shade of background.

See 
![icjmj](https://cloud.githubusercontent.com/assets/3521959/8744443/1d18ec92-2c6f-11e5-90cd-00e3eefdbfac.jpg)

Like that not only look different enough per album view everything could look aligned and tidy.

**Comment by jez500** [comment]
Not a feature and I don't like the way it looks either. Is on the todo list.

**Comment by jez500** [comment]
Fixed, Sorry you aren't around to see it @un1versal - Thanks for all your help and support with this project, RIP
