### ISSUE TITLE
HTML entities in title tags are getting double encoded

### ISSUE THREAD

**Issue by jamieburchell** [xbmc/chorus2#371]
### Describe the bug
HTML entities in title tags are getting double encoded.

### Screenshots 
Here are some links or screenshots to help explain the problem:

![Untitled-1](https://user-images.githubusercontent.com/3270426/66688090-104c1700-ec7d-11e9-8b4f-6f24b5d22c17.png)

The HTML is `<a href="#music/album/101" title="The &amp;#39;C&amp;#39; EP">The 'C' EP</a>`

Note the & is incorrectly encoded.

### Your Environment
Used Operating system:

 - Used browser(s): Chrome
 - Operating system version/name: Windows 10
 - Kodi version and platform: v18.3 OSMC
 - Chorus2 version: 18.x-2.4.6

**Comment by malard** [comment]
dupe/same as #470  which i've fixed
