### ISSUE TITLE
Last.Fm scrobbler support

### ISSUE THREAD

**Issue by simba83** [xbmc/chorus2#38]
It would be nice if we could have scrobbler support for last.fm.
http://www.lastfm.com/api

**Comment by jez500** [comment]
This depends on the lastfm addon and how it implements things, probably be a while until I can get to this one (or any specific addon functionality) as there is many more core priority items but if anyone wants to submit a PR for getting it working, I am happy to mentor/assist in getting it integrated.

**Comment by malard** [comment]
as lastfm is not an official addon, the official web interface will have nothing to do with it :) if that changes, we can look at it
