### ISSUE TITLE
Chorus uses thumb instead of poster for movies!?

### ISSUE THREAD

**Issue by Uatschitchun** [xbmc/chorus2#383]
### Describe the bug
Here is a clear and concise description of what the problem is:
Chorus is using moviename-thumb.jpg as cover image instead of the available moviename-poster.jpg which leads to ugly (too large) views.

It doesn't do it for all movies so I can't tell what's leading to this behavior!?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
From my understanding chorus should use movie-poster if available

## Actual Behavior
For some movies chorus displays movie-thumb not movie-poster

## Possible Fix
use poster if available and only use thumb as a fallback

### To Reproduce
Add movies to kodi with thumbs and posters and view them in chorus.

### Screenshots
Here are some links or screenshots to help explain the problem:
![Screenshot_20191121_223843](https://user-images.githubusercontent.com/25088926/69443130-1a6a3680-0d4e-11ea-9233-7fa253d15808.png)
![Screenshot_20191121_223909](https://user-images.githubusercontent.com/25088926/69443139-1dfdbd80-0d4e-11ea-8022-bd11d238b109.png)
![Screenshot_20191122_173405](https://user-images.githubusercontent.com/25088926/69443237-4eddf280-0d4e-11ea-955c-9c0ec06f26f8.png)

### Your Environment
Used Operating system: Linux

 - Used browser(s): Opera, Firefox
 - Operating system version/name: Ubuntu Bionic 18.04 / docker (linuxserver/kodi-headless)
 - Kodi version and platform: 18.4
 - Chorus2 version: 2.4.6

**Comment by enen92** [comment]
should be fixed by: https://github.com/xbmc/chorus2/pull/392

**Comment by Uatschitchun** [comment]
Ah nice ;)
Sadly I'm not updating to v19 anytime before it's release, so I can't test
