### ISSUE TITLE
Allow filtering by tags

### ISSUE THREAD

**Issue by tazeat** [xbmc/chorus2#385]
## Feature suggestion
**Detailed Description**
The Web UI currently has the ability to edit tags by editing movie items and manually typing in tags (an ability to pick an existing tag would also be nice, but that's another feature), but lacks an obvious way to filter by them.

The tags option does not show up under filter in all movies or tv shows (although similar features such as Sets do). 

This ironically is the opposite of other remote clients such as Yatse which allow browsing by tags, but have no ability to set them.

### Context
Filtering by tags allow users who use them to organize their files to find their media faster and more efficiently. Ie using Child tags for children movies or a Christmas tag to easily find all your Christmas movies year after year. Tags, unlike playlists, are stored in the SQL movie database and thus are easier to sync across multiple clients that use a shared database and appear to be gaining more use in the wild as it becomes a more supported feature on the desktop UI. 

### Possible Implementation
Easiest solution would be to add tags to the items a filter can be created with. 

Alternatively a more user friendly option might even allow tags to be selected as a section like All movies section is and provide easy access to a users separate tags closer to how they are chose in the standard desktop UI. 

### Additional context, screenshots or links
Current high level sections:
![image](https://user-images.githubusercontent.com/8007808/71038061-d57bba80-20d5-11ea-93dd-b196c6b0efcc.png)

Current filter options:
![image](https://user-images.githubusercontent.com/8007808/71037960-a1a09500-20d5-11ea-9cb6-2d09cb58255e.png)

**Comment by tazeat** [comment]
I went ahead and made PR #386 for this, was much easier than I expected to add.

**Comment by malard** [comment]
already implemented
