### ISSUE TITLE
HTML artifacts in displaying album year

### ISSUE THREAD

**Issue by erewhon-smith** [xbmc/chorus2#395]
## Expected Behavior

Should display album year under album title in view of an artist's albums.

## Actual Behavior

Shows

"<a href="#music/albums?year=1994"

in place of album year "1994".

## Environment
 - Used browser: Chromium from Arch Linux
 - Operating system running Kodi: Raspbian Buster
 - Kodi version and platform: Kodi 18.5

**Comment by kikendo** [comment]
Yup I have the same issue.

**Comment by arigit** [comment]
+1, still present on kodi 18.8

**Comment by arigit** [comment]
actually this is a duplicate of #358

**Comment by arigit** [comment]
Thanks @nagubal!

**Comment by arigit** [comment]
@erewhon-smith  the fix for this has been merged in master and will be included in the next release (20.x). This issue can be closed now.

**Comment by enen92** [comment]
It will be included in v19.1 of Kodi which is about to be released (and also in v20 if the default webinterface is not replaced ) . Thanks for the fixes.
