### ISSUE TITLE
HDMI CEC not for Chorus2

### ISSUE THREAD

**Issue by drrak** [xbmc/chorus2#399]
_Translator:_
Can Chorus2 somehow not use the HDMI CEC function? It's annoying when I turn off the TV and when changing e.g. an album in Chorus2, the TV turns on.

_RPi4, Kodi 18.6, LibreELEC 9.2.1_

**Comment by enen92** [comment]
That's likely an internal call kodi makes somewhere within the json-rpc call. I'd suggest you bring this as an issue in xbmc/xbmc and not chorus2
