### ISSUE TITLE
Add setting to choose what to show as label (e.g. folder/file name)

### ISSUE THREAD

**Issue by kzar79** [xbmc/chorus2#408]
## Feature suggestion
**Detailed Description**

Currently the web interface uses the "label" property of the folder/files returned by the API. It is hardcoded.
Some users (e.g. me) might prefer to see the actual folder/file name, because the label is based on tags, and some users (e.g. me) do not like/use tags. 
This is particularily important in the Browse mode, because users expect to see the real folder structure with the real folder and file names, not a confusing structure based on labels based on tags.

What I propose is to add a setting for Chorus, in which the user can choose what to see as label. Probably the choices are only "label" and "filename"... It could be just a switch "Show file names as labels".

Then, in the method to create the html label, the code should check this setting and decide if to show the "label" field or the "file" file (well, the part after the last slash).

It is not difficult, if you want I can do it.

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
please go ahead and do it and submit a PR but this change would be extensive
