### ISSUE TITLE
Kodi sometimes crash when accessing music library in Chorus 2 webpage just after startup

### ISSUE THREAD

**Issue by franckgaga** [xbmc/chorus2#423]
### Describe the bug

Kodi sometimes crash when accessing music library in Chorus 2 webpage (remotely with firefox through ipaddress:port# and clicking "Music") just after Kodi startup. I'm using LibreELEC 9.2.4 on a Raspberry PI 3B+. The crash happen about 1 out of 3 times. It never crashes with Kore application on Android.

## Expected Behavior

It should not crashes.

## Actual Behavior

Kodi crashes and it restart after about 30 seconds.

### To Reproduce

1. Reboot computer (Kodi automatically start on LibreELEC)
2. On another computer connected on the local network, open firefox an go to url : ipadress:port#, where ipadress is the raspberry PI ip address and port# is Chorus 2 interface port number.
3. In chorus page, click on "Music" to browse music library
4. About 1 out of 3 times, Kodi crashes and automatically restart after ~30 seconds

### Debuglog

The debuglog can be found here:
System log : http://ix.io/2w2p
Crash log : http://ix.io/2w2o

### Screenshots
Here are some links or screenshots to help explain the problem:

![screenshot](https://user-images.githubusercontent.com/34136215/92268533-8dddce80-eeb0-11ea-9494-f6228c233cd0.png)

### Your Environment
Used Operating system:

 - Used browser(s): firefox 80.0
 - Operating system version/name: Linux Mint 20 Cinnamon
 - Kodi version and platform: 18.8 on LibreELEC 9.2.4 (raspberri Pi 3B+)
 - Chorus2 version: 19.x-2.4.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by gsantner** [comment]
This also happens for me since recent update(s), happens very very often that kodi just force quits without further notice..when I visit chorus webpage. Happens for me on both, music and videos/movies.

Especially a deal breaker if you are currently half way through watching a movie and boom suddenly it force quits, not even saves the playback position and the others of family ask why I had to restart it now...

**Comment by RubenTeixeira** [comment]
For me this is happening only on mobile. Tested with Chrome and Firefox on Android, Chrome and Safari on IOS.
Sometimes it may not crash and just doesn't load the song. It loads the song list, but not the song.

**Comment by malard** [comment]
This will be an issue with Kodi rather than Chorus and Chorus is just a web interface on top of the JSONRPC, please re-raise this in the correct project
