### ISSUE TITLE
Time display broken for PVR

### ISSUE THREAD

**Issue by akloeckner** [xbmc/chorus2#424]
### Describe the bug
Here is a clear and concise description of what the problem is:

I have the very same problem as described in #306 . I'm on recent Firefox. I just installed KODI afresh.

When I open the PVR page in Chorus, I get lot of "nan" displays. It works fine in Edge, displaying times and dates there.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Dates should be shown correctly (as dates) also in Firefox.

## Actual Behavior

Dates are shown as "nan".

### To Reproduce

1. open chorus website
2. open PVR page
3. open a channel page

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

Firefox:
![grafik](https://user-images.githubusercontent.com/7125061/93690899-49704680-fade-11ea-87b8-976b623a4560.png)
Edge:
![grafik](https://user-images.githubusercontent.com/7125061/93690906-58ef8f80-fade-11ea-9ce7-0f627ba832df.png)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Used browser(s): firefox 80.0.1
 - Operating system version/name: Win 10
 - Kodi version and platform:18.7 on OSMC on raspberry3
 - Chorus2 version:18.x-2.4.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
please re-open if this is still an issue in Kodi 20+
