### ISSUE TITLE
access individual addon settings from chorus2?

### ISSUE THREAD

**Issue by npmstart-pray** [xbmc/chorus2#440]
## Feature suggestion
**Detailed Description**

trying to find an alternative method to input my netflix credentials into CastagnaIT's Netflix add-on - his script for generating a key doesn't seem to be working for me, so at the suggestion I saw on that dev's Issues, I decided to try chorus2.  I can't seem to find the way to launch access to its settings 

### Context

That add-on is a way for users to have a similar Netflix experience on their kodi as they do on netflix-approved devices.  But not everyone has a smart tv or wants to watch on their phone, so for cable cutters who have subscribed, it's a godsend.  unfortunately, for some reason, signing in to netflix with email/pwd stopped working using the kodi remote app.  The Netflix add-on written by that dev has an associated python script that continues to not work for me on my linux desktop, and 2 different windows computers, so accessing the authentication of the addon via its settings would be most helpful

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
kodi official addons will only be coded to talk to official addons, as this is not an official addon natively supporting this is outside of scope

**Comment by npmstart-pray** [comment]
lol I've long since moved on, matey.
