### ISSUE TITLE
Cannot Edit TV Show Season

### ISSUE THREAD

**Issue by NoralK** [xbmc/chorus2#441]
### Describe the bug
Here is a clear and concise description of what the problem is:

Cannot "Edit" a TV Season.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Ability to edit the TV Season.

## Actual Behavior

Nothing happens

### To Reproduce

1.  From TV Shows go to "TV Show(Stargate SG-1)" - this shows all the seasons.
2.  Click the vertical ellipsis and then Edit ... nothing happens.  Where as from TV Shows click on the vertical ellipsis and you can edit the TV Show.
3.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - Used browser(s):
       Chrome, Edge, IE
 - Operating system version/name:
       LibreELEC (Leia) 9.2.6
 - Kodi version and platform:
       LibreELEC (Leia) 9.2.6
 - Chorus2 version:
      18.X-2.4.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
What information in Season are you trying to edit? Seasons are virtual in Kodi, so there is nothing to edit.

**Comment by NoralK** [comment]
Image but would also like Title like in TV interface.

**Comment by KarellenX** [comment]
Ok, understand. I think Season Rename was implemented in Kodi after this web interface was released, and it was never updated. (and probably never will be)

Work has commenced on the new Web Interface (call it Chorus 3 if you like) but it just needs someone to complete the work. It is a GSOC project, so we are hoping it will be competed this year...
https://kodi.wiki/view/Google_Summer_of_Code/2021#Finish_the_new_web_interface

As this is not a bug, rather a missing feature/feature request, I'll go ahead and close the issue, but it is still open for comments.

**Comment by NoralK** [comment]
Okay thank you for the information.
