### ISSUE TITLE
Clean Library button is missing in multiple browsers in Windows, and in Firefox on Linux.

### ISSUE THREAD

**Issue by gannon345** [xbmc/chorus2#442]
### Describe the bug
Here is a clear and concise description of what the problem is:

In Google Chrome on Linux, in settings -> media, there's a clean library button for video and music. 
If you go into the same settings panel in Firefox on Linux, or either browser when on Windows, for whatever reason that button is not there. I've tested and confirmed this with and without an ad blocker.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Clean library button should be visible under settings -> media in the web UI.

## Actual Behavior

Clean video and clean music buttons are available in Linux if using Chrome browser, but is otherwise missing for other browsers, and altogether in Windows.

### To Reproduce

1. Open Google Chrome in Linux. 
2. Browse to Chorus2 UI for Kodi and go to settings cog, then media
3. Clean library button for video and/or music will be there.
4. Open other browser in Linux, or any browser in Windows 10
5. Browse to Chorus2 UI for Kodi and go to settings cog, then media
6. Clean library button option will be missing.

### Debuglog

The debuglog can be found here:
paste.kodi.tv/amavepipis.kodi

### Screenshots
Here are some links or screenshots to help explain the problem:

Clean library options working: https://i.imgur.com/jF6VJxU.png
Clean library options not working: https://i.imgur.com/4VuXuNd.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

------------------
System Information
------------------
      Time of this report: 5/11/2021, 19:46:48
             Machine name: [REDACTED]
               Machine Id: [REDACTED]
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: English (Regional Setting: English)
      System Manufacturer: [REDACTED]
             System Model: Nuc6i3SYH
                     BIOS: SYSKLi35.86A.0073.2020.0909.1625 (type: UEFI)
                Processor: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (4 CPUs), ~2.3GHz
                   Memory: 8192MB RAM
      Available OS Memory: 7890MB RAM
                Page File: 5024MB used, 4145MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 144 DPI (150 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.0928 64bit Unicode

-------------------------------------------------------------------------------

 - Used browser(s): Google Chrome, Mozilla Firefox
 - Operating system version/name: Windows 10 (Kodi System and clients accessing server), Kubuntu Linux 20.10 (client accessing web server), Xubuntu 20.10 (client accessing web server).
 - Kodi version and platform: Multiple versions of Kodi 18, as well as Kodi 19, and 19.1
 - Chorus2 version: Whatever was included in the Kodi versions listed.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
this is not a bug, you are not in expert settings level in the other browser (note the variable amount of menu options on the left)
