### ISSUE TITLE
Feature Request: Select output device

### ISSUE THREAD

**Issue by FredFirestone** [xbmc/chorus2#448]
## Feature suggestion
**Detailed Description**

I want to use kodi [running on a raspberry pi with a HifiBerry audio hat connected to a stereo] as a radio player controlled by remote or better yet chorus. However I've not found a working solution to switch output device:
- Chorus on my mobile always only opens web settings
- Chorus on my computer allows me to open "Settings -> System" but regardless of selection I never managed to switch audio to my stereo. Even if it was properly connected before just opening the page breaks connection
- (I've not found any other remote allowing to switch output device)
- (I'm using AudioProfile Add-On, but even automatic switching doesn't work via Web)

### Context

Kodi is quite flexible which is what I use: I watch TV (received by a stick) with output via TV, I listen to music with output via bluetooth speaker, I listen to radio (also received by a stick) with output via stereo. I really think it's currently unneccessarly complicated to switch audio output device.

### Possible Implementation

It should really be very easily accessible, similiar to selecting output level.

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
Happy to receive a PR for this, however this is so niche to your use case that we will not consider it for general development
