### ISSUE TITLE
Kodi19.3 couldn’t connect to kodi addon repository 

### ISSUE THREAD

**Issue by DZ65367709** [xbmc/chorus2#453]
### Describe the bug
Here is a clear and concise description of what the problem is:

I dowloaded kodi19.3,but couldn’t connect to the addon repository with a VPN connection. If I didn’t using the VPN and connecting directly to the internet , the add-on repository would be reached. AsI have to use a VPN connection,  which causes I can’t connect to the repository every time.
That’s it.Thanks for help.

PS: when I established a VPN connection, and the repository couldn’t be connected to, yet all addon could connect to the internet normally.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Used browser(s):
 - Operating system version/name:
 - Kodi version and platform:
 - Chorus2 version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by DZ65367709** [comment]
PS: when I established a VPN connection, and the repository couldn’t be connected to, yet all addon  could connect to the internet normally.

**Comment by basilgello** [comment]
Sounds like a DNS resolver issue within VPN. Please supply information about VPN provider and OS you use at least.

**Comment by DZ65367709** [comment]
Thank you for your response.
I just curious that other apps are normal with same devices and settings.
I use VPN application of shadowsocksr on OS of openwrt, which is set as transparent gateway.

Thanks.

**Comment by malard** [comment]
closing as has nothing to do with chorus2
