### ISSUE TITLE
be able to install new apps via the web interface

### ISSUE THREAD

**Issue by lakshaysethi** [xbmc/chorus2#456]
## Feature suggestion
**Detailed Description**

user should be able to install new applications in Kodi through the web UI

### Context

I am running Kodi server headless using Docker I only have access to the web UI

### Additional context, screenshots or links
Here are some relevant links or screenshots:

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
I feel this is outside the scope of what chorus2 is, if you want this capability it should be in its own addon
