### ISSUE TITLE
Not showing ' character correctly

### ISSUE THREAD

**Issue by gillesoorts** [xbmc/chorus2#470]
### Describe the bug
Here is a clear and concise description of what the problem is:

Not showing ' character correctly

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Shows the ' character

## Actual Behavior

Shows & # 3 9 ; (without spaces)

### To Reproduce

1.
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

https://www.dropbox.com/s/u959c8qfj2q3985/Screenshot%202022-04-12%20at%2018.33.19.png?dl=0

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Used browser(s): Safari
 - Operating system version/name: Synology DSM 6
 - Kodi version and platform: 19.4 Synology
 - Chorus2 version: 19.x-2.4.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by malard** [comment]
it appears this has been partially fixed by @enen92 for tv episodes, however not for movie cards
