### ISSUE TITLE
[Feature] Playing Kodi-side playlists

### ISSUE THREAD

**Issue by DerDonut** [xbmc/chorus2#49]
I searched for this feature in Chorus 1, but it seems not to be supported, so i make a feature suggestion for Chorus 2:
When selecting "Playlists" in the Web UI, the playlists which are saved on the Kodi host system should be displayed - asides to the local browser-based playlists. These playlist should be playable by kodi itself. The lists would be global for all users of the web interface.

**Comment by jez500** [comment]
I can't find an api call giving kodi playlists other than what is playing. I would like this too.

**Comment by jmastel** [comment]
Drat, I was hoping for this exact feature, it would be really handy to update Kodi Playlists from Chorus.

**Comment by DerDonut** [comment]
i've looked that up and i think I found a way:
The playlists can be retrieved on a file basis with a special directory:
http://<server address>/jsonrpc?request={"jsonrpc":"2.0","method":"Files.GetDirectory","params":{"directory":"special://musicplaylists"},"id":6}
On my kodi server (running Kodi 16 RC1) this worsk well. I get those playlists as file paths. Like "special://profile/playlists/music/<name>.m3u"

**Comment by jmastel** [comment]
The way I usually retrieve the playlist files Is I remote into the Pi using VNC and navigate to the file, and if I want to make changes remotely I edit the .m3u file. I also have a shell script that updates my main playlist from a directory when run. 

```
 #!/bin/bash

PRE=#EXTINF:0,
FILES="/home/vnc/Desktop/Content/"
PLAY="/home/vnc/Desktop/video/Main Playlist.m3u"
cat /dev/null > "$PLAY"
echo "#EXTM3U" >> "$PLAY" 
for f in "$FILES"*
do
     actuallyf=${f##*/}
     echo "$PRE$actuallyf"  >> "$PLAY"
     echo "$DIR$f"  >> "$PLAY"

done
```


I know you can play Kodi playlists from Chorus, you just can't save them from Chorus. Maybe Chorus saves it's playlists to a folder somewhere in the file system...

**Comment by arigit** [comment]
Just to add my +1 to the support of Kodi's Advanced Playlists - playlists that can give either a list of Albums or a list of Songs.
Both Yatse and Music Pump support them.

Use case: Classical music collection with thousands of albums. One ".xsp" playlist file for each Composer, that matches all albums whose Composer contain a given string. E.g Beethoven.xsp will produce a list of all albums that contain Beethoven in the Composer tag. This works fine in Yatse for instance. Hoping we can get the functionality in Chorus2

Thanks

**Comment by jez500** [comment]
You can now access saved Kodi playlists via the browser. 

You can also export playlists created in chorus as `.m3u` and then save to `special://playlists` to access via the Kodi ui.
