### ISSUE TITLE
Does not appear to work with V20 of Kodi

### ISSUE THREAD

**Issue by topcats** [xbmc/chorus2#541]
### Describe the bug
Here is a clear and concise description of what the problem is:

After windows upgrade of Kodi from V19 to V20 with default web interface is reporting 'file not found' error
The api socket is still working ok
This has happened on multiple windows installs.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normal 'Chorus 2' interface control

## Actual Behavior

the web browser reports back 'file not found'

### To Reproduce

1. Start Kodi
2. setup web interface with username / password if you want
3. browse to local address

### Debuglog

The debuglog can be found here:
2023-03-10 11:59:08.538 T:11716    info <CWebserver[8080]>: Started
2023-03-10 11:59:27.094 T:11716    info <CWebserver[8080]>: Skipped 1 duplicate messages..
2023-03-10 11:59:27.094 T:11716    info <CWebserver[8080]>: Stopped
2023-03-10 11:59:27.113 T:11716    info <CWebserver[8080]>: Started

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - Used browser(s): Edge
 - Operating system version/name: Windows 10 pro, Windows 10 Enterprise
 - Kodi version and platform: Starting Kodi (20.0 (20.0.0) Git:20230115-389e701cb9). Platform: Windows NT x86 64-bit
 - Chorus2 version: 19.x-2.4.8
 - 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by fuzzard** [comment]
This is fixed in nexus nightlies and will be available for 20.1
