### ISSUE TITLE
[Request] Read and use the shortcuts key from the keymap.xml

### ISSUE THREAD

**Issue by SubEdict** [xbmc/chorus2#549]
## Feature suggestion
**Detailed Description**

I'm using chorus2 on a laptop to remotely control a PC that I'm usually play Kodi with my prefer keymap.xml shortcuts. 
While the shortcut "T" for toggle subtitles work on the laptop keyboard, the other shortcuts that exist only on the PC are not.

### Context

I'm using these shortcuts setting on the PC for years and it's great:
(Roaming\Kodi\userdata\keymaps)
```
<keymap>
	<global>
		<keyboard>
			<F5>ActivateWindow(SubtitleSearch)</F5>
			<left mod="ctrl">subtitledelayminus</left>
			<right mod="ctrl">subtitledelayplus</right>
			<left mod="ctrl,shift">audiodelayminus</left>
			<right mod="ctrl,shift">audiodelayplus</right>
		</keyboard>
	</global>
</keymap>
```

### Possible Implementation

Is there any way to connect the keymap.xml to Chorus2?
Maybe let the users add manually or direct to xml file in Chorus2 setting?

### Additional context, screenshots or links
That's all, everything else is fantastic.

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment]
overriding the keyboard behaviour in a browser is ill advised, it will have an impact on accessibility and general navigational behaviours. If someone wishes to create an enhancement that permits this with a specific setting to toggle the feature on then we can review it into the project

**Comment by SubEdict** [comment]
Never mind, thanks anyway.
