### ISSUE TITLE
Sections bar

### ISSUE THREAD

**Issue by mizaki** [xbmc/chorus2#6]
This uses a lot of white space (mostly), my idea is to make it a vertical and have the Sections, Filter, Sort, etc. dropdown (over the content) to make better use of the space.

**Comment by jez500** [comment]
The plan is to make that side bar disappear on smaller screens, then have a button to toggle its visibility, it is fine on large screens as there is space to spare.  Ideally I want this to be a standard layout for anything which has secondary nav/filters so when new pages are added the layout is ready to go. 

Definitely still needs some work.

**Comment by jez500** [comment]
Sidebar behaves quite nicely now, hides on small screen, smaller on medium screen and full size on large screen. At some point in the very distant future, I might add additional themes where the sidebar is horizontal but for now it does the job well
