### ISSUE TITLE
Feature request - Extend facility to allow editing of TV shows, episodes and albums and tracks.. .

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#68]
Currently (2.0.8) you can only Edit this for movies, TV shows dont have such option.

**Comment by jez500** [comment]
Songs, artists and albums too.

**Comment by un1versal** [comment]
and to allow all these to happen in the single movie view, single tv show, single season, single episode, single album, single track

atm only when viewing all movies theres the menu/options button.

**Comment by dernalis** [comment]
Maybe allow select Poster, Fanart, Cover and so....

**Comment by jez500** [comment]
@dernalis I would really like to be able to update images too, and I had a brief go at it, but seems very difficult. 

If anyone knows of some code that can do it, point me in its direction.

**Comment by dernalis** [comment]
AFAIK, We just need the list of image URLs and set them with **VideoLibrary.SetMovieDetails**, **VideoLibrary.SetTVShowDetails**, etc.

Maybe libraries like https://github.com/edwellbrook/node-tvdb and https://github.com/cavestri/themoviedb-javascript-library/ could help.

**Comment by un1versal** [comment]
> @dernalis I would really like to be able to update images too, and I had a brief go at it, but seems very difficult.
> 
> If anyone knows of some code that can do it, point me in its direction.

One person that may know is @milhousevh (sorry milhouse for pestering :D)

**Comment by MilhouseVH** [comment]
Not sure what info you need, but to set movie artwork (in this case a clearlogo):
```
{"jsonrpc": "2.0", "params": {"art": {"clearlogo": "nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Zombieland (2009)[BDRip]-logo.png"}, "movieid": 2395}, "method": "VideoLibrary.SetMovieDetails", "id": "libSetDetails"}]
```

**Comment by dernalis** [comment]
Thanks, @milhousevh , but, we're trying to do is some thing like scraping media info sites (tmdb, tvdb, etc) to get images URLs and be able to set them to library fields.

Please, forget my previous comment. It will not work due cross-domain permission issues.

**Comment by jez500** [comment]
Thanks for the tips @MilhouseVH 

There is a fair hunk of work around this one, @un1versal @dernalis probably going to be low priority until most of the other things are sorted

**Comment by un1versal** [comment]
low priority is better than no priority at all :D

**Comment by micle546** [comment]
check out the doc on XBMC NFO files.
AFAIK, osmc will parse the nfo file and use the images that it points to.

I'm using http://www.movie-renamer.fr/ for movies
And http://www.tvrename.com/ for tv shows, however I haven't explored it's xbmc.NFO file options yet.

I've been able to change the displayed images though them before

**Comment by dernalis** [comment]
This example should help with the movies part: http://ibacor.com/demo/themoviedb-api-using-jquery-ajax

At least to scrap for covers and backdrops.

**Comment by dernalis** [comment]
This could be useful for Movies: https://www.smashingmagazine.com/2012/02/beginners-guide-jquery-based-json-api-clients/

Not sure if this could help for TVShows too: https://api-beta.thetvdb.com/swagger

**Comment by jez500** [comment]
This was added as of 2.3.9, unfortunately the API doesn't allow us to set artwork on audio library items yet but it works really well for items in the video library
