### ISSUE TITLE
Feature request - Stop scanning (video,audio) library

### ISSUE THREAD

**Issue by un1versal** [xbmc/chorus2#69]
The only thing missing is the label (Stop scanning) to be updated when you start a Video/Audio scan,

![capture](https://cloud.githubusercontent.com/assets/3521959/11397643/dcde7b04-9372-11e5-96e8-c511e61989e4.PNG)

How it works (not documented thx wsnipex for tip) You press **Scan video/audio library** scan start press it again scan should stop. as this is calling the builtins apparently.

**Comment by jez500** [comment]
Problem with this one is there is currently no way of knowing "if currently scanning" (correct me if I am wrong) so it is a bit tricky to implement to work with any user opening Chorus at potentially any time. That said maybe we could just toggle "scan" and "stop" for the current user.

**Comment by un1versal** [comment]
No idea if scanning can be detected, Im sure it is since kodi does it (this function/label update happens in kodi). not idea how, again millhouse is probably the best person to ask this, so Ill leave it to you to ping him this time, 

Its only a label switch here needed.

**Comment by jez500** [comment]
This is not supported by the API, might add it in when it is
