### ISSUE TITLE
Cast calling

### ISSUE THREAD

**Issue by mizaki** [xbmc/chorus2#7]
Calling the Cast property is very expensive and should be avoided (along with streamdetails) unless explicitly used. For example only when viewing episode details. Returning all TV show even on an i750 that I use for Kodi takes 8.58s with 262 shows.

Can argue about cache hitting but lower powered (Pi) are going to timeout. :)

**Comment by jez500** [comment]
I know! but It is the only way to get the filter by actor functionality working, which I love.  Maybe should add it as a setting for those expensive filters (default to off).

How the filters work is directly on the collection client side so all the data needs to be present for the filters to work.  The api wasn't flexible enough to get all the functionality I wanted, eg. allow multiple filters applied.

**Comment by mizaki** [comment]
Use JIT (if that's using the term correctly). Not sure how or if (it must be!) this is possible but build a custom RPC query when using filters. As I understand you (I think backbonejs?) can alter and add to the collection by itself. This also ties in to an idea I had of "slow" building the cache (see below). The same as the global search but limited to the library in question.

Slow building cache:
To start with you retrieve the bare minimum of data and then as long as there are free requests (I remember only 4 at a time) it retrieves more information of say 10 items. It just keeps doing that until the cache is full. Keeping it in sync with Kodi without websockets should be reasonably possible by just checking the limits on each library. Worth feature suggestion?

Hopefully I'm making sense for a Sunday.

**Comment by mizaki** [comment]
For now I think the best thing to do is call in chunks, say 50-100 items at a time. And have a render on update. Still trying to figure out the best way to do it. That way we can at least avoid a time out.

**Comment by jez500** [comment]
I have been thinking about this more too, api not allowing multiple filters is the biggest road block. I think a setting is the best short term fix. But if you come up with something else that works then all for it!
