### ISSUE TITLE
YouTube/History is alphabeticaly sorted, not by 'last seen'

### ISSUE THREAD

**Issue by vitstradal** [xbmc/chorus2#71]
Hi,

When accessing to YouTube history, files are sorted not by last seen (what would I expect), but by name. Is it possible to add button `unsorted` or add explicit exception `do-not-sort-youtube-history`?

I think, key rpc query is:

``` json
{"jsonrpc":"2.0",
 "method":"Files.GetDirectory",
 "id":"1449044597784",
 "params":[
   "plugin://plugin.video.youtube/channel/mine/playlist/HLLNxxxxxxxxxxxx/",
   "video",
   ["title","file","mimetype","thumbnail"],
   {"method":"label","order":"ascending","ignorearticle":true}
 ]
}
```

By experimenting, correct order is obtained by:

``` json
{"jsonrpc":"2.0",
 "method":"Files.GetDirectory",
 "id":"1449044597784",
 "params":[
   "plugin://plugin.video.youtube/channel/mine/playlist/HLLNxxxxxxxxx/",
   "video",
   ["title","file","mimetype","thumbnail"],
   {}
 ]
}
```

**Comment by jez500** [comment]
I agree,

Although, anything not core, eg. addons, is going to require an [addon module](https://github.com/jez500/chorus2/tree/master/src/js/apps/addon) to override default settings (in general we want everything else to sort by title) so this is put on hold until a youtube module is created by me (or some kind contributer) to add tweaks for specific addons.

**Comment by vitstradal** [comment]
... OR: There could be common (not youtube-plugin-specific) possibility to change sort order. Indeed sometimes  (not always) I want sort by modification time to see last added|downloaded videos|music.

**Comment by jez500** [comment]
Sort order added in 2.4.0
