### ISSUE TITLE
Thumbs up for tv series.

### ISSUE THREAD

**Issue by freshfruitig** [xbmc/chorus2#74]
First off i would like to say i really like this Web interface, and it's by far the best one around!.

I used chorus 1 for a long time and i really liked the options to give thumbs up to tv series.
In Chorus 2 i can give a movie a thumb up but i don't have this option when checking my series.

Thanks for this awesome interface!

Kind regards,
Mark

**Comment by jez500** [comment]
Hey @freshfruitig 

Thanks for the kind words. This is definitely on the cards, infact probably the next thing I will look at.

**Comment by freshfruitig** [comment]
Hi jez500

How are you doing?

Love all the improvements you made in the last few updates.
Do you have an ETA for the thumbs up or favourites for series.

Thanks again for you're awesome work.
Will definitely send you a couple of beers soon ;)

Mark

**Comment by freshfruitig** [comment]
Hi Jez500,

How are you?
Could you give me an update about the thumbs up?

Thanks in advance?

**Comment by jez500** [comment]
Hey @freshfruitig 
Just for you, It will be the next thing I add  ;)
I know I said that before, but got sidetracked with other things

**Comment by freshfruitig** [comment]
@jez500 Thanks a lot! looking forward to using this feature again.

**Comment by jez500** [comment]
Hey @freshfruitig as of 2.3.6 you can thumbs up tv shows, yay!
