### ISSUE TITLE
Kodi Music Library has additional data to access

### ISSUE THREAD

**Issue by DaveTBlake** [xbmc/chorus2#81]
Just hoping to draw your attention to some additions to Kodi music database. Processing and storing extra tags such as composer, conductor, DJMixer, TMCL, TIPL, so more artists hled and many way to filter them.

Maybe Chorus will display this stuff? Perhaps you have some input to make on API desihn here http://forum.kodi.tv/showthread.php?tid=256962

**Comment by henkhend** [comment]
This is my attempt to 'upvote' this as I'd love to see the addition of 'composer' to the list of sections for the music library (that's part of what this request is about, isn't it?). I've got a large classical music collection and now that Kodi uses the composer tag, I'm looking forward to controllers like Chorus to support them as well.

Regards,
Henk

**Comment by malard** [comment]
there is a request for classical music support, i'm closing this in favour of that ticket
