### ISSUE TITLE
play next track automatically in browser

### ISSUE THREAD

**Issue by bendschs** [xbmc/chorus2#87]
i noticed that chorus will only play the next track in the playlist in local browser mode if i focus the browser window (if the browserwindow is not active next track wont be played).

is this normal? i use safari 9.0.3 on el capitan (10.11.3).

cheers bendsch ...

**Comment by jez500** [comment]
Hi @bendschs 
Does this happen in chrome or firefox?

**Comment by bendschs** [comment]
hello jez, it happens in safari (mac osx).

**Comment by jez500** [comment]
Hi @bendschs, 
That is not what I asked: "Does this happen in chrome or firefox?"

**Comment by bendschs** [comment]
it does also happen in firefox and chrome.

**Comment by jez500** [comment]
I can't replicate this anymore, might be related to another issue that has since been fixed so I am going to close this for now
