### ISSUE TITLE
Label to identify Media Center in main page

### ISSUE THREAD

**Issue by dernalis** [xbmc/chorus2#98]
Working with several Media Centers could be easier with a label to identyfy them.

This label should be easily taken from system/services/device name.
![livingroom](https://cloud.githubusercontent.com/assets/3215655/13538895/4d34f418-e24d-11e5-856c-c7980eb29dd9.png)

**Comment by dernalis** [comment]
Add some color schemes to the theme could be also awesome, but I understand it could be a lot of work and out of roadmap or, at least far, far away.

**Comment by jez500** [comment]
Hi @dernalis this has been added in 2.3.6 - you need enable it via `chorus > settings > web interface > appearance` It uses the device name which you can also set via the settings page if you need to
